/* SPDX-License-Identifier: GPL-3.0-only
 * Copyright (C) 2026 bilibili@卡布奇诺ultra
 */
'use client';
import ObservationPanel from './ObservationPanel';
import {studyRun,studyOptions,studyComplete,restoreStudyPacket} from './observation';
import ChapterReview from './ChapterReview';
import ChallengePanel from './ChallengePanel';
import {choiceChain} from './experience-hints';
import SaveComparison from './SaveComparison';
import SceneAction from './SceneAction';
import {createSceneInput} from './scene-input';
import {DIFFICULTY_GUIDANCE,growthGuidance,objectiveGuidance} from './player-guidance';
import StoryItemSummary from './StoryItemSummary';
import PanelBody from './PanelBody';
import TouchSettings from './TouchSettings';
import RecordsPanel from './RecordsPanel';
import {encounterLabel} from './encounter-labels';
import ResultRecord from './ResultRecord';
import {touchSettings,supportsTouchLock,setTouchAim,clearTouchLock} from './touch-controls';
import {elapsedBattle} from './record-rules';
import {withProgressRecord,settleRunResult,resultAlreadyClaimed,compareRunRecord,formatRecordTime,printableText} from './records';
import {compatibilityEntry} from './delivery-names';
/* oxlint-disable react/react-compiler -- This view bridges a mutable, event-driven battle engine. React Compiler is not enabled; rules-of-hooks and exhaustive-deps remain checked. */
import React,{useEffect,useLayoutEffect,useRef,useState} from 'react';
import {Button} from '../components/ui/button';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '../components/ui/dialog';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '../components/ui/tabs';
import {Slider} from '../components/ui/slider';
import {createRun,restoreRun} from './run-factory';
import {EQUIPMENT} from './expedition';
import CultivationPanel,{CultivationSummary} from './CultivationPanel';
import {traitDescription,traitValueLine,traitTierName} from './descriptions';
import {catalogItemState} from './catalog-state';
import {stepBattle,MAX_FRAME} from './frame-step';
import {comboDescription,traitComboBenefit} from './combo-description';
import {coreDescription} from './core-description';
import {needsCultivationUpgrade,cultivationStatus} from './cultivation';
import {planMetaRefund,planGardenRefund,planCultivationUpgrade} from './respec';
import {CORES,defaultGarden,EXPEDITIONS} from './expedition-data';
import {BossIdentity,ExpeditionPanel,Cinematic,Garden,SupplyChooser,RouteStrip,AtlasSprite,StoryReplay} from './ExpeditionPanel';
import {loadArt,Renderer,sprite} from './art';
import {Sound} from './audio';
import {PATHS,TRAITS,COMBOS,RELICS,CONSUMABLES,ENEMIES,CHAPTERS,EVENTS,DIFFICULTIES,LORE_URLS,initialSave,modText} from './data';
import {JOURNAL,STORY_ITEMS} from './journal';
import {layoutFor} from './encounters';
import {GAME_VERSION,GAME_ARC} from './version';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription} from '../components/ui/alert-dialog';
import {SaveVault,MAX_SAVE_IMPORT_BYTES,SAVE_KEY,recoveryImportCandidates,checkpointDirty,readableSaveError,normalizeSave} from './save-store';
import {STARTERS,starterStatus,starterDetails} from './starters';
import {capturePointer} from './pointer-input';
import CombatButton from './CombatButton';
import {practiceFocusRelease,practiceFocusCleared} from './practice';
import StarterPreview from './StarterPreview';
import CombatStatus from './CombatStatus';
import RunStats,{runConfiguration,allyDeployment} from './RunStats';
import {DamageReport,RecentHits,SigilReport} from './CombatReport';
import {chapterName,legacyChapterAchievement} from './chapter-names';
import {hasReserveRest,reserveRestBase,traitText,BALANCE_VERSION} from './balance';
import {directFocus} from './targeting';
import HelpReader from './HelpReader';
import RecoveryPanel from './RecoveryPanel';
import PracticePanel from './PracticePanel';
import {revisedGrowth,traitReadiness,xpCostFor} from './growth-rules';
import {defeatAdvice} from './presentation-feedback';
import {DEFAULT_KEYS,bindingError,invalidBindings} from './keybindings';
import './game.css';
import GameErrorBoundary,{crashExports} from './GameErrorBoundary';
const MENU_CHAPTERS=CHAPTERS.map((c,i)=>({...c,name:EXPEDITIONS[i].name}));

const keyLabel=k=>({Space:'空格',ControlLeft:'左Ctrl（不可绑定）',ControlRight:'右Ctrl（不可绑定）',AltLeft:'左Alt（不可绑定）',AltRight:'右Alt（不可绑定）',MetaLeft:'左Command（不可绑定）',MetaRight:'右Command（不可绑定）',ShiftLeft:'左Shift',ShiftRight:'右Shift',Enter:'回车',Comma:'逗号',Period:'句号'}[k]||k.replace('Key','').replace('Digit','').replace('Numpad','小键盘 '));
const clock=t=>Math.floor(t/60).toString().padStart(2,'0')+':'+Math.floor(t%60).toString().padStart(2,'0');
const percent=(x,max)=>Math.max(0,Math.min(100,x/max*100));
function Btn({children,className='',...props}){return <Button className={'fr-btn '+className} {...props}>{children}</Button>;}
function Chip({children,color}){return <span className="chip" style={{color}}>{children}</span>;}
function SpriteView({art,index=0,enemy=false,height=70}){
 const ref=useRef(null);useEffect(()=>{const c=ref.current;if(!c||!art)return;const ctx=c.getContext('2d');ctx.clearRect(0,0,c.width,c.height);ctx.imageSmoothingEnabled=false;sprite(ctx,enemy?art.foes[index]:art.heroes[index],c.width/2,c.height-2,height);},[art,index,enemy,height]);
 return <canvas ref={ref} width={height*1.5} height={height+4} className="sprite-view" aria-hidden="true"/>;
}
function achievementList(save){
 const rows=[];for(let i=0;i<6;i++)rows.push({name:'历经·'+chapterName(i),desc:'通过此章',done:(save.completed||[]).includes(i)||(save.achievements||[]).includes(legacyChapterAchievement(i))});
 for(const n of [1,100,300,600,1000,2000,5000,10000])rows.push({name:'斩敌 '+n,desc:'累计击杀达到 '+n,done:save.kills>=n});
 for(const n of [6,12,24,36,48,72])rows.push({name:n+' 剑齐出',desc:'单局剑数达到 '+n,done:save.best>=n});
 for(const n of [1,5,10,20])rows.push({name:'雷霆 '+n,desc:'单局施放神雷 '+n+' 次',done:save.history.some(h=>h.thunders>=n)});
 for(let i=0;i<6;i++)rows.push({name:PATHS[i].name+'有成',desc:'以此起手完成主篇',done:save.history.some(h=>h.won&&['story','seed'].includes(h.mode)&&h.path===i)});
 for(const n of [1,6,12,24,36])rows.push({name:'洞府修持 '+n,desc:'解锁 '+n+' 个洞府节点',done:save.meta.length>=n});
 for(const n of [1,2,3,5,10])rows.push({name:'问道 '+n,desc:'完成主篇 '+n+' 次',done:save.wins>=n});return rows.map(r=>({...r,done:r.done||(save.achievements||[]).includes(r.name)}));
}
// Render errors fall back to a read-only export screen instead of an empty page.
export default function Game(){return <GameErrorBoundary><GameView/></GameErrorBoundary>;}
function GameView(){
 const studyReturnRef=useRef(null);
 const practiceOfferRef=useRef(null),settingsOrigin=useRef('home'),lodgeOrigin=useRef('home'),practiceReturn=useRef(null),practiceAcknowledged=useRef(false);
 const resultRecordsRef=useRef(false),[resultRecords,setResultRecords]=useState(false),[compactHUD,setCompactHUD]=useState(false),[spaceLimited,setSpaceLimited]=useState(false);
 const sceneInput=useRef(createSceneInput()),cinematicFocusRef=useRef(null),hudSummaryRef=useRef(false),[hudSummary,setHudSummary]=useState(false);
 const [importCandidates,setImportCandidates]=useState([]),[inputDevice,setInputDevice]=useState('keyboard'),[landscapeDismissed,setLandscapeDismissed]=useState(false);
 const [recoveryInfo,setRecoveryInfo]=useState({issue:null,candidates:[]}),[practiceOffer,setPracticeOffer]=useState(null);
 const startRef=useRef(null),aimPointer=useRef(null),aimStart=useRef(null),headerRef=useRef(null);
 const sceneTimer=useRef(null),bossVisualUntil=useRef(0),choiceFocusRef=useRef(null),heldKeysRef=useRef(new Set()),blockedChoiceKeys=useRef(new Set()),footerRef=useRef(null),mainRef=useRef(null),canvasRef=useRef(null),battleRef=useRef(null),rendererRef=useRef(null),soundRef=useRef(null),saveRef=useRef(initialSave()),artRef=useRef(null);
 const [art,setArt]=useState(null),[ready,setReady]=useState(false),[error,setError]=useState(''),[save,setSave]=useState(initialSave());
 const [page,setPage]=useState('home'),[scene,setScene]=useState(null),[,redraw]=useState(0),[toast,setToast]=useState('');
 const [path,setPath]=useState(0),[difficulty,setDifficulty]=useState(0),[mode,setMode]=useState('story'),[seed,setSeed]=useState(''),[chapter,setChapter]=useState(0),[codex,setCodex]=useState('traits');
 const [risk,setRisk]=useState(null),riskRef=useRef(null),cancelRiskRef=useRef(null),[help,setHelp]=useState(null),helpRef=useRef(null),[saveStatus,setSaveStatus]=useState('loading'),vaultRef=useRef(null),pendingSaveRef=useRef(null),conflictRef=useRef(false);
 const [runtimeFault,setRuntimeFault]=useState(null),runtimeFaultRef=useRef(null),settingsDirtyRef=useRef(false),checkpointBackupRef=useRef(false);
 const [replace,setReplace]=useState(null),[bind,setBind]=useState(null),[keymap,setKeymap]=useState(DEFAULT_KEYS);
 const pageRef=useRef(page),bindRef=useRef(bind),keyRef=useRef(keymap),toastTimer=useRef(null),joy=useRef({x:0,y:0});
 crashExports.pending=()=>pendingSaveRef.current?.next||null;practiceOfferRef.current=practiceOffer;resultRecordsRef.current=resultRecords;pageRef.current=page;bindRef.current=bind;keyRef.current=keymap;startRef.current=start;
 function cancelBinding(){bindRef.current=null;setBind(null);}
 // System clears (Esc, blur, dialogs) never count as the player releasing focus; practice step 5 needs a real release.
 function clearAim(){aimPointer.current=null;aimStart.current=null;const run=battleRef.current;if(run){run.clearDashInput();practiceFocusCleared(run);run.input.focus=false;run.input.aim=null;run.input.touchAim=false;}redraw(v=>v+1);}
 function releaseAim(){const run=battleRef.current;if(run)practiceFocusRelease(run);clearAim();}
 useLayoutEffect(()=>{if(page!=='settings'){bindRef.current=null;setBind(null);}},[page]);
 function presentScene(next){clearTimeout(sceneTimer.current);const run=battleRef.current,delay=bossVisualUntil.current-performance.now();if(next&&next!=='pause'&&delay>0){setScene(null);sceneTimer.current=setTimeout(()=>{if(run===battleRef.current&&!runtimeFaultRef.current)setScene(run.scene||next);},delay);}else setScene(next);}
 // Battle-phase toasts stay at most 1.2 s (C-1); menu/save messages keep 3.5 s.
 function message(text,duration=3500){setToast(text);clearTimeout(toastTimer.current);toastTimer.current=setTimeout(()=>setToast(''),duration);}
 function describeSave(value){const c=value?.checkpoint;return c?(c.options?.rulesVersion===3?EXPEDITIONS[c.chapter]?.name:CHAPTERS[c.chapter]?.name)+' · '+(c.options?.rulesVersion===3?'节点 '+(c.wave+1):c.wave<3?'第 '+(c.wave+1)+' 波':'主要遭遇')+' · '+Math.min(72,c.level)+' 剑':'没有待续玩的战斗';}
 function showRisk(payload){const current=battleRef.current,previous=riskRef.current;const wasPlaying=current?.modeState==='battle';current?.pause();clearAim();joy.current={x:0,y:0};const value={...payload,resumeOnCancel:payload.resumeOnCancel??(wasPlaying||!!previous?.resumeOnCancel),replaced:!!previous};riskRef.current=value;setRisk(value);
  // A dialog replaced in place (e.g. by another window's write) keeps its confirm disabled briefly and refocuses cancel, so a click meant for the old question cannot confirm the new one.
  if(previous){requestAnimationFrame(()=>cancelRiskRef.current?.focus());setTimeout(()=>{if(riskRef.current===value){const armed={...value,replaced:false};riskRef.current=armed;setRisk(armed);}},600);}}
 function cancelRisk(){const previous=riskRef.current;riskRef.current=null;setRisk(null);if(previous?.resumeOnCancel)battleRef.current?.resume();}
 function confirmRisk(){const pending=riskRef.current;if(!pending?.run||pending.replaced)return;riskRef.current=null;setRisk(null);pending.run();}
 function refreshRecovery(){try{const issue=vaultRef.current?.inspectRecovery()||null;setRecoveryInfo({issue,candidates:vaultRef.current?.recoveryCandidates()||[]});if(issue&&!conflictRef.current)setSaveStatus('recovery');}catch(error){setSaveStatus('error');message(error.message||'恢复资料暂时无法读取，原记录仍保留');}}
 function openSettings(){if(pageRef.current!=='settings')settingsOrigin.current=pageRef.current==='play'?'play':'home';battleRef.current?.pause();clearAim();heldKeysRef.current.clear();joy.current={x:0,y:0};refreshRecovery();setPage('settings');}
 function openLodge(){lodgeOrigin.current=pageRef.current==='journey'?'journey':'home';setPage('lodge');}
 function closeSettings(){cancelBinding();heldKeysRef.current.clear();joy.current={x:0,y:0};if(battleRef.current)battleRef.current.options.settings=saveRef.current.settings;setPage(settingsOrigin.current==='play'&&battleRef.current?'play':'home');}
 function adoptRecovery(candidate){if(!candidate.save)return;showRisk({title:'采用「'+candidate.label+'」？',description:'这将结束当前战斗并替换续玩、心得、修持、章节、成绩和设置。确认后保留现有主档、备份、异常资料及所选原文。'+(candidate.discarded?.includes('checkpoint')?'这份原文的续玩损坏，将放弃该局续玩。':'所选有效续玩保留。')+(candidate.recordReport?'成绩保留 '+candidate.recordReport.kept+' 条；隔离 '+candidate.recordReport.isolated+' 条成绩、'+candidate.recordReport.isolatedReceipts+' 项重复或无效凭据。'+(candidate.recordReport.unknownSchema?'成绩格式未知，整份隔离，不猜测转换。':''):'')+(candidate.historyDropped?'历史记录丢弃 '+candidate.historyDropped+' 条无效条目，原文仍保留。':''),footnote:'覆盖前完整保留当前主档、备份、恢复日志与所选原文；确认时重新核对全部记录源。',comparison:{current:pendingSaveRef.current?.next||saveRef.current,target:candidate.save,currentUnknown:vaultRef.current.corrupt||!!recoveryInfo.issue&&!vaultRef.current.expectedRaw},detail:'心得 '+candidate.save.insight+' · 斩敌 '+candidate.save.kills+' · 修持 '+candidate.save.meta.length+' 项 · 已完成章节 '+candidate.save.completed.length+' · '+describeSave(candidate.save),confirm:'确认采用并保留前态',resumeOnCancel:false,run:()=>persist(candidate.save,{recoveryCandidate:candidate,onSuccess:()=>{battleRef.current=null;setScene(null);setPage('home');setImportCandidates([]);refreshRecovery();message('已采用所选记录，前态及原文可在设置中恢复或导出');}})});}

 function finishPractice(){battleRef.current?.pause();clearAim();heldKeysRef.current.clear();joy.current={x:0,y:0};battleRef.current=null;setScene(null);setPage('journey');practiceAcknowledged.current=true;const chosen=practiceReturn.current;if(chosen){setPath(chosen.path);setDifficulty(chosen.difficulty);setMode(chosen.mode);setSeed(chosen.mode==='seed'?chosen.seed:'');setChapter(chosen.chapter);}practiceReturn.current=null;message('练习已结束，出发配置已保留；点击启程开始正式历练');}
 function setSaved(value){saveRef.current=value;setSave(value);setKeymap({...DEFAULT_KEYS,...value.keymap});settingsDirtyRef.current=false;setSaveStatus(vaultRef.current?.recoveryIssue?'recovery':'saved');conflictRef.current=false;}
 function loadLatest(expectedSnapshot){try{const value=vaultRef.current.loadConfirmed(expectedSnapshot);setSaved(value);refreshRecovery();pendingSaveRef.current=null;runtimeFaultRef.current=null;setRuntimeFault(null);battleRef.current=null;setScene(null);setPage('home');message('已载入最新记录');}catch(error){if(error.code==='stale-preview'){previewLatest();message(error.message);}else saveFault(error);}}
 function previewLatest(){try{const target=vaultRef.current.previewLatest(),complete=!!target.save&&!target.discarded.length;const idle=!battleRef.current&&!pendingSaveRef.current;showRisk({title:'另一窗口更新了存档',description:idle?'本页已停止写入。本页没有进行中的战斗或待保存结果，可直接载入磁盘最新记录；本页旧状态不会覆盖它。':'本页已经暂停，旧状态停止写入。载入磁盘最新记录会结束本页当前战斗；尚未保存的本次结果将被放弃，可先导出本次待保存记录。',comparison:{current:pendingSaveRef.current?.next||saveRef.current,target:target.save,currentUnknown:vaultRef.current.corrupt},detail:complete?'确认时重新核对主档、备份、恢复日志与隔离原文。':'磁盘记录不可直接载入：'+(target.reason||target.status)+'。请查看恢复资料。',exportLabel:pendingSaveRef.current?'导出本次待保存记录':undefined,onExport:pendingSaveRef.current?exportPendingResult:undefined,footnote:idle?'载入只读取磁盘记录；本页没有会被放弃的内容。':'放弃的只是本页未保存的战斗与结果；磁盘记录不会被本页覆盖。',confirm:complete?'载入最新记录':'查看恢复资料',run:complete?()=>loadLatest(target.expectedSnapshot):()=>{if(JSON.stringify(vaultRef.current.snapshot())!==JSON.stringify(target.expectedSnapshot)){previewLatest();message('磁盘记录已变化，请重新核对');return;}vaultRef.current.expectedRaw=target.expectedSnapshot.primary;vaultRef.current.corrupt=true;vaultRef.current.inspectRecovery();openSettings();},resumeOnCancel:false});}catch(error){message(readableSaveError(error));}}
 // Browser error names (e.g. QuotaExceededError) survive the SaveError wrapper through `cause`.
 function faultName(error){const name=error?.cause?.name||(error instanceof Error?error.name:'');return name&&!['Error','SaveError'].includes(name)?name:'';}
 function saveFault(error,next=null,options={}){
  // The pending record is frozen at fault time; later battle updates must not rewrite what export/retry will send.
  // Only a valid ordinary write becomes the pending base; recovery adoptions stay explicit and are never stacked
  // under later battle results, and a record that fails validation is offered for export instead of endless retry.
  const frozen=next?structuredClone(next):null;const recovery=!!(options.recoveryCandidate||options.resolveRecovery),rejected=!!frozen&&!writableRecord(frozen);
  if(frozen&&!recovery&&!rejected)pendingSaveRef.current={next:frozen,options:{backup:!!options.backup,allowCorrupt:!!options.allowCorrupt}};
  if(error.code==='recovery'||error.code==='raw-capacity'){refreshRecovery();openSettings();setSaveStatus('error');message(error.message,8000);return;}
  setSaveStatus(error.code==='conflict'?'conflict':'error');
  if(error.code==='conflict'){conflictRef.current=true;previewLatest();}
  else if(rejected)showRisk({title:'本次记录未通过存档校验',description:readableSaveError(error)+'。重试不会成功，磁盘上的原记录没有被覆盖。',detail:'可先导出这份未保存的记录用于排查；关闭提示后继续使用磁盘上的最近记录。',exportLabel:'导出未保存记录',onExport:()=>exportRecord(frozen),footnote:'导出的是本页内存中未通过校验的记录，不是磁盘旧档。',resumeOnCancel:false});
  else{const name=faultName(error),invalid=error.code==='invalid';showRisk({recovery:invalid,title:invalid?'旧存档暂时无法读取':'保存未成功',description:error.message+(name?'（浏览器报告：'+name+'）':'')+'。关闭提示后仍会保留原记录。',detail:frozen?'本次改动与结算凭据尚未写入磁盘；可先「导出本次待保存记录」，再「重试保存」。':'可在设置中恢复备份，或导出原始记录。',exportLabel:frozen?'导出本次待保存记录':undefined,onExport:frozen?()=>exportRecord(frozen):undefined,footnote:frozen?'导出的是内存中的最新待保存记录（含本次改动与凭据），不是磁盘旧档；磁盘上的原记录未被覆盖。':invalid?'「导出原文」保存磁盘上的原始记录汇总；确认前不会修改或清空它。':'「导出备份」保存磁盘上最近成功保存的记录；本页尚未写入的内容不在其中。',confirm:frozen?'重试保存':undefined,run:frozen?()=>persist(frozen,options):undefined,resumeOnCancel:false});}
 }
 function persist(fn,options={}){
  if(studyRun(battleRef.current)){message('观察期间不写正式资料；请先结束观察再保存设置或处理正式记录。');return false;}
  // Updates build on the unsaved pending record, so a later successful write can never silently drop it.
  const pending=typeof fn==='function'&&!options.discardPending?pendingSaveRef.current:null;
  if(pending)options={...options,backup:!!(options.backup||pending.options.backup),allowCorrupt:!!(options.allowCorrupt||pending.options.allowCorrupt)};
  const next=typeof fn==='function'?fn(pending?structuredClone(pending.next):saveRef.current):fn;next.achievements=achievementList(next).filter(a=>a.done).map(a=>a.name);
  try{const value=options.recoveryCandidate?vaultRef.current.adoptRecovery(next,{expectedSnapshot:options.recoveryCandidate.expectedSnapshot,sourceRaw:options.recoveryCandidate.sourceRaw||options.recoveryCandidate.raw}):options.resolveRecovery&&vaultRef.current.recoveryIssue?vaultRef.current.resolveRecovery(next):vaultRef.current.commit(next,options);setSaved(value);pendingSaveRef.current=null;options.onSuccess?.(value);return true;}catch(error){saveFault(error,next,options);return false;}
 }
 function openHelp(kind){battleRef.current?.pause();clearAim();helpRef.current=kind;setHelp(kind);}
 function closeHelp(){helpRef.current=null;setHelp(null);}
 function restoreBackup(){try{if(vaultRef.current?.recoveryIssue){openSettings();message('请选择待采用的有效记录；处理前会保留完整前态');return;}const candidate=vaultRef.current.recoveryCandidates().find(c=>c.id==='backup');if(!candidate?.save){message('暂时没有可恢复的有效备份');return;}if(candidate.discarded.length){adoptRecovery(candidate);return;}showRisk({title:'恢复上次备份？',description:'这将替换续玩与长期进度；本页未保存的战斗或结果将被放弃。确认前可先导出。覆盖前完整保护当前主档、备份、恢复日志和所选原文。',comparison:{current:pendingSaveRef.current?.next||saveRef.current,target:candidate.save},detail:'请核对两份记录；确认时重新核验所有记录源。',footnote:'恢复前保护当前主档、备份、恢复日志与所选原文，可在设置中再次恢复或导出。',confirm:'确认恢复备份',run:()=>persist(candidate.save,{recoveryCandidate:candidate,onSuccess:()=>{battleRef.current=null;setScene(null);setPage('home');message('备份已恢复，替换前态已保留');}}),resumeOnCancel:false});}catch(error){saveFault(error);}}
 function retryPendingResult(){const pending=pendingSaveRef.current;if(pending)persist(pending.next,pending.options);}
 function exportRecord(next){downloadText(JSON.stringify(next,null,2),'青竹剑阵_本次待保存记录.json');message('已导出本次完整待保存记录，含结算凭据；当前磁盘未改变');}
 function exportPendingResult(){const next=pendingSaveRef.current?.next;if(!next){message('没有待保存的本次记录');return;}exportRecord(next);}
 function writableRecord(next){try{normalizeSave(structuredClone(next));return true;}catch{return false;}}

 function previewSettings(key,value){if(studyRun(battleRef.current))return;const next={...saveRef.current,settings:{...saveRef.current.settings,[key]:value}};saveRef.current=next;setSave(next);settingsDirtyRef.current=true;}
 function updateSettings(key,value){persist(s=>({...s,settings:{...s.settings,[key]:value}}));}
 function updateTouchSettings(key,value){const run=battleRef.current;run?.pause();clearAim();heldKeysRef.current.clear();joy.current={x:0,y:0};const live=settingsOrigin.current==='play'&&run&&supportsTouchLock(run)&&key==='touchLock';let checkpoint;
  if(live&&run.mode!=='training'&&!studyRun(run)){checkpoint=run.serialize();checkpoint.options={...checkpoint.options,touchLockEnabled:value,touchLockUsed:run.options.touchLockUsed||value};}
  persist(s=>({...s,settings:{...s.settings,[key]:value},...(checkpoint?{checkpoint}: {})}),{onSuccess:()=>{if(live&&run===battleRef.current){run.options.touchLockEnabled=value;run.options.touchLockUsed||=value;}redraw(v=>v+1);}});
 }
 // Full deflection at min(45px, visual radius): the small landscape/compact sticks reach full speed at their own rim (round-2 C-2).
 function joystickPoint(e){const r=e.currentTarget.getBoundingClientRect(),scale=r.width/Math.max(1,e.currentTarget.offsetWidth),radius=Math.min(45*scale,r.width/2)||45*scale;return {x:(e.clientX-r.left-r.width/2)/radius,y:(e.clientY-r.top-r.height/2)/radius};}
 function exportRecovery(){try{const bundle=vaultRef.current.recoveryBundle();if(!bundle.records.length&&!bundle.pendingBackup&&!bundle.primary&&!bundle.backup){message('没有已隔离的原始记录');return;}downloadText(JSON.stringify(bundle,null,2),'青竹剑阵_原始记录汇总.json');message('已发起原始记录汇总下载，当前存档未改变');}catch{message('读取恢复记录失败，原文仍保留');}}
 function restoreProfileOnly(){refreshRecovery();const candidate=vaultRef.current?.recoveryCandidates().find(c=>c.id==='primary'&&c.save);if(candidate){adoptRecovery(candidate);return;}openSettings();message('主记录的长期进度也无法读取，只能导出原文；可导入其他存档，或从首页「保留原文并开启新历练」');}
 // Unreadable primary with no valid candidate: one visible path to a confirmed new run that keeps every raw record.
 function preserveAndStart(){const readable=recoveryInfo.candidates.filter(c=>c.save&&['primary','backup'].includes(c.id));showRisk({recovery:true,title:'保留原文并开启新历练？',description:'当前记录待处理：'+(recoveryInfo.issue||'记录无法读取')+'。确认后先自动导出原始记录汇总（主档、备份、异常日志与隔离原文），再进入出发配置；启程时会再次确认，并在建立新存档前完整保留这些原文，可在设置中恢复或导出。',detail:readable.length?readable.map(c=>c.label+'：'+describeSave(c.save)).join('；'):(vaultRef.current?.corrupt?'原记录无法读取摘要，将完整保留原文；新历练从空白长期进度开始。':'原记录无法读取摘要，将完整保留原文；新历练使用当前可读的长期进度。'),confirm:'导出原文并前往出发配置',footnote:'确认前不改变任何记录；取消保留当前状态。',resumeOnCancel:false,run:()=>{exportRecovery();setPage('journey');}});}
 function isolatedCount(){try{return vaultRef.current?.rawRecords().length||0;}catch{return 0;}}
 function clearIsolated(){let records,expectedSnapshot;try{expectedSnapshot=vaultRef.current.snapshot();records=vaultRef.current.rawRecords();}catch(error){message(error.message||'读取隔离原文失败，原文仍保留');return;}if(!records.length){message('没有已隔离的原文');return;}
  showRisk({recovery:true,title:'清理 '+records.length+' 份隔离原文？',description:'这些是异常处理前保留的旧主档、备份与导入原文，清理后无法再从设置恢复它们。确认前可先「导出原文」保存汇总；清理不改变当前主档、备份、恢复日志与续玩。',detail:'隔离原文最多保留 12 份，相同原文只保留一份；满额时停止覆盖，不会自动删除。确认将删除当前列表全部 '+records.length+' 份隔离原文。',confirm:'确认清理隔离原文',footnote:'清理只删除已展示的隔离原文；取消、写入失败或确认前其他窗口改动记录时保留原文。清理后请重新选择恢复记录或重新导入，再次核对后采用。',resumeOnCancel:false,run:()=>{try{vaultRef.current.clearRawRecords(expectedSnapshot);setImportCandidates([]);refreshRecovery();message('隔离原文已清理；主档、备份与日志未改变，请重新选择恢复记录或重新导入',8000);}catch(error){message(error.message||'清理未完成，原文仍保留');}}});}

 function recoverRuntime(){showRisk({title:'载入最近保存节点？',description:'这将结束当前异常的战斗，放弃最近一次保存之后的进度。磁盘记录不会被覆盖，可以先导出备份。',detail:describeSave(saveRef.current),confirm:'确认载入最近节点',run:()=>{runtimeFaultRef.current=null;setRuntimeFault(null);battleRef.current=null;continueSaved({confirmed:true});},resumeOnCancel:false});}
 function runtimeFailure(error){if(runtimeFaultRef.current)return;const fault={message:String(error?.message||error),time:Date.now()};runtimeFaultRef.current=fault;setRuntimeFault(fault);setScene(null);const active=battleRef.current;if(active){active.clearDashInput();active.modeState='pause';active.scene='pause';active.input={x:0,y:0,focus:false};}joy.current={x:0,y:0};showRisk({title:'本局出现异常，已暂停',description:'战斗与画面更新已停止，最近的保存记录没有被覆盖。可先导出备份，再确认载入最近节点。',detail:describeSave(saveRef.current),confirm:saveRef.current.checkpoint?'载入最近节点':undefined,run:saveRef.current.checkpoint?recoverRuntime:undefined,resumeOnCancel:false});}
 const eventRef=useRef(null);eventRef.current=ev=>{
  if(ev.type==='formation-ready')rendererRef.current?.showFormationReady(battleRef.current);
  if(ev.type==='boss-defeat'){rendererRef.current?.showBossDefeat(ev.effect);bossVisualUntil.current=performance.now()+720;}
  if(ev.type==='update')redraw(v=>v+1);
  if(ev.type==='scene'){if(ev.scene)joy.current={x:0,y:0};sceneInput.current.invalidate();if(ev.scene)clearAim();if(['choice','pause','cinematic'].includes(ev.scene))blockedChoiceKeys.current=new Set([...heldKeysRef.current].filter(k=>['Space','Enter'].includes(k)));if(ev.scene){clearTimeout(toastTimer.current);setToast('');}presentScene(ev.scene);setReplace(null);redraw(v=>v+1);}
  if(ev.type==='toast')message(ev.text,battleRef.current?.modeState==='battle'?1200:3500);
  if(ev.type==='sound')soundRef.current?.play(ev.name);
  if(ev.type==='shake'&&rendererRef.current)rendererRef.current.shake=ev.value;
  const b=battleRef.current;
  if(studyRun(b)){if(ev.type==='checkpoint')b.studyCheckpoint=structuredClone(ev.checkpoint);if(ev.type==='finish'){presentScene('result');redraw(v=>v+1);}return;}
  if(ev.type==='checkpoint'&&b?.mode==='endless'&&b.recordState?.completedLoops>0){const view=compareRunRecord(saveRef.current,b.summary());if(view.kind!=='recorded')b.loopComparison=view;}
  if(ev.type==='checkpoint'&&b?.mode!=='training')persist(s=>({...withProgressRecord(s,b.summary()),checkpoint:ev.checkpoint,best:Math.max(s.best,Math.min(72,b.level))}),{backup:checkpointBackupRef.current});
  if(ev.type==='chapter'&&['story','seed'].includes(b?.mode))persist(s=>({...s,unlocked:Math.max(s.unlocked,Math.min(5,ev.chapter+1)),completed:[...new Set([...(s.completed||[]),ev.chapter])],best:Math.max(s.best,Math.min(72,b.level))}));
  if(ev.type==='finish'){
   presentScene('result');if(!b.resultFeedback)b.resultFeedback={...(b.mode==='endless'&&b.loopComparison?.entry?.loops===ev.summary.recordDetails?.completedLoops?b.loopComparison:compareRunRecord(saveRef.current,ev.summary)),saved:false};
   if(b?.mode!=='training'){if(!resultAlreadyClaimed(saveRef.current,ev.summary))persist(s=>settleRunResult(s,{...ev.summary,seen:[...b.seen]}),{onSuccess:()=>{b.resultFeedback.saved=true;redraw(v=>v+1);}});else{b.resultFeedback.saved=true;b.resultFeedback.restored=true;if(saveRef.current.checkpoint?.expedition?.runId===b.runId)persist(s=>({...s,checkpoint:null}));}}redraw(v=>v+1);
  }
 };
 function exportObservation(packet){downloadText(JSON.stringify(packet,null,2),packet.kind+'-'+packet.snapshot.options.path+'.json');message('已发起观察包下载；请确认文件保存成功');}
 async function importObservation(e){const file=e.target.files?.[0];e.target.value='';if(!file)return;try{if(file.size>MAX_SAVE_IMPORT_BYTES)throw Error('观察包超过 8 MiB');const b=restoreStudyPacket(await file.text(),ev=>eventRef.current?.(ev));showRisk({title:'进入观察包？',description:'正式在场局暂停并保留，结束观察后返回；正式续玩、待保存结果与保护资料保持。未导出的当前观察笔记会丢失，请先导出。',confirm:'进入该观察',resumeOnCancel:false,run:()=>{if(battleRef.current&&!studyRun(battleRef.current))studyReturnRef.current=battleRef.current;battleRef.current=b;setPage('play');if(studyComplete(b)){b.finish(false,'前两章对照体验完成');}else if(b.modeState==='battle')b.pause();setScene(b.scene);}});}catch(error){message('观察包未采用：'+error.message);}}
 function start(options={}){
  if(needsCultivationUpgrade(saveRef.current)&&options.metaRulesVersion===undefined&&!(options.rulesVersion<=2)){upgradeCultivation(()=>start(options));return;}
  const chosenMode=options.mode||mode;if(chosenMode==='endless'&&saveRef.current.wins<=0){message('完成一次主篇或完整定种胜局后开放无尽新局；已有无尽可继续');return;}const day=new Date().toISOString().slice(0,10);
  const chosen={path,difficulty,mode:chosenMode,seed:chosenMode==='seed'?printableText(seed).trim()||day:day+'-'+Math.floor(Math.random()*9999),chapter:chosenMode==='replay'?chapter:0,meta:saveRef.current.meta,settings:saveRef.current.settings,rulesVersion:3,metaRulesVersion:3,supply:(saveRef.current.garden||defaultGarden()).selected,...options};
  delete chosen.skipPractice;
  if(chosen.mode!=='training'&&!options.skipPractice&&!practiceAcknowledged.current&&!(saveRef.current.guidesSeen||[]).includes('practice-v1')&&!vaultRef.current?.recoveryIssue&&!vaultRef.current?.corrupt){battleRef.current?.pause();clearAim();setPracticeOffer(chosen);return;}
  const launch=()=>{soundRef.current?.start();const b=createRun(chosen,e=>eventRef.current?.(e));b.accountCleared=saveRef.current.wins>0;b.showGuide=!(saveRef.current.guidesSeen||[]).includes(chosen.path);
   const activate=()=>{if(chosen.studyVersion===1&&battleRef.current&&!studyRun(battleRef.current))studyReturnRef.current=battleRef.current;clearTimeout(sceneTimer.current);bossVisualUntil.current=0;rendererRef.current?.clearBossDefeat();clearTimeout(toastTimer.current);setToast('');runtimeFaultRef.current=null;setRuntimeFault(null);battleRef.current=b;setPage('play');setScene('intro');setReplace(null);};
   if(chosen.mode==='training'||chosen.studyVersion===1){activate();return;}
   persist(v=>({...v,checkpoint:b.serialize(),guidesSeen:[...new Set([...(v.guidesSeen||[]),chosen.path,'practice-v1'])]}),{backup:true,allowCorrupt:true,discardPending:true,resolveRecovery:!!vaultRef.current?.recoveryIssue,onSuccess:()=>{activate();refreshRecovery();}});
  };
  if(chosen.studyVersion===1){if(battleRef.current){showRisk({title:'进入前两章对照体验？',description:'正式在场局暂停并保留，结束观察后返回；正式续玩和待保存结果保持。当前观察未导出的笔记会丢失。体验使用独立空修持配置，不结算正式奖励。',confirm:'进入观察',run:launch});}else launch();return;}
  if(chosen.mode==='training'&&!runtimeFaultRef.current&&!checkpointDirty(battleRef.current,saveRef.current)){launch();return;}
  if(vaultRef.current?.recoveryIssue||runtimeFaultRef.current||saveRef.current.checkpoint||vaultRef.current?.corrupt||checkpointDirty(battleRef.current,saveRef.current)||pendingSaveRef.current){showRisk({title:chosen.mode==='training'?'结束当前战斗并试剑？':'开启新历练？',description:vaultRef.current?.recoveryIssue?'当前存在待处理恢复资料。确认后先保留旧主档、唯一备份和异常原文，再建立新历练；旧记录可在设置中恢复。':chosen.mode==='training'?'本波未保存进度将回退；试剑台不会替换最近的正式存档。':vaultRef.current?.corrupt?'旧记录目前无法读取。新开会建立新存档，并保留旧记录原文；请先导出原始记录。':(pendingSaveRef.current?'当前还有未保存的结果；新开后将放弃这份待保存结果，请先重试或导出。':'')+'新历练将替换目前的续玩记录。洞府修持、已解锁章节和成就保留；该局未正式结算的药园研究点将被放弃。',detail:vaultRef.current?.recoveryIssue?(recoveryInfo.candidates.filter(c=>c.save&&['primary','backup'].includes(c.id)).map(c=>c.label+'：心得 '+c.save.insight+' · 斩敌 '+c.save.kills+' · '+describeSave(c.save)).join('；')||'原记录无法读取摘要，将完整保留原文；新历练使用当前可读的长期进度。'):describeSave(saveRef.current),confirm:chosen.mode==='training'?'确认进入试剑台':'确认开启新历练',footnote:chosen.mode==='training'?'试剑台不写入正式存档；未保存的本波进度会回退到最近节点。':vaultRef.current?.recoveryIssue||vaultRef.current?.corrupt?'建立新存档前完整保留旧主档、备份、异常日志与隔离原文，可在设置中恢复或导出。':'新局建立前备份当前主档；已结算的长期进度保留，未保存的本波进度回退。',run:launch});}else launch();
 }
 function continueSaved(options){if(vaultRef.current?.recoveryIssue){openSettings();message('继续历练前，请先确认采用要保留的记录');return;}const confirmed=options?.confirmed===true;
  if(!confirmed&&(pendingSaveRef.current||checkpointDirty(battleRef.current,saveRef.current))){showRisk({title:'放弃未保存的进度并继续？',description:'本页还有尚未写入磁盘的进度或结果。继续历练会从磁盘上的最近安全节点重新开始，并放弃这些未保存内容；可先导出本次待保存记录。',detail:'最近节点：'+describeSave(saveRef.current),exportLabel:pendingSaveRef.current?'导出本次待保存记录':undefined,onExport:pendingSaveRef.current?exportPendingResult:undefined,confirm:'放弃并继续最近节点',footnote:'磁盘上的最近节点与长期进度不会被改写。',resumeOnCancel:false,run:()=>continueSaved({confirmed:true})});return;}
  if(confirmed)pendingSaveRef.current=null;try{if(vaultRef.current.changedElsewhere()){saveFault({code:'conflict'});return;}soundRef.current?.start();const b=restoreRun(saveRef.current.checkpoint,e=>eventRef.current?.(e));b.options.settings=saveRef.current.settings;battleRef.current=b;if(b.isExpedition&&b.modeState==='battle')b.pause();setPage('play');setScene(b.scene);}catch(error){message('战斗记录无法恢复：'+readableSaveError(error)+'；请导出备份或在设置中处理');}}
 function home(){if(studyRun(battleRef.current)){showRisk({title:'结束本次观察？',description:'未导出的观察进度和笔记将丢失。正式续玩、待保存结果与保护资料保持；可取消后先导出观察包。',confirm:'结束观察',resumeOnCancel:false,run:()=>{const prior=studyReturnRef.current;studyReturnRef.current=null;battleRef.current=prior;setScene(prior?.scene||null);setPage(prior?'play':'journey');joy.current={x:0,y:0};}});return;}const leave=()=>{clearTimeout(sceneTimer.current);bossVisualUntil.current=0;rendererRef.current?.clearBossDefeat();clearTimeout(toastTimer.current);setToast('');runtimeFaultRef.current=null;setRuntimeFault(null);battleRef.current=null;setScene(null);setPage('home');joy.current={x:0,y:0};};
  if(runtimeFaultRef.current||settingsDirtyRef.current||checkpointDirty(battleRef.current,saveRef.current)||pendingSaveRef.current){showRisk({title:'返回山门？',description:'当前战斗将结束，续玩会回到最近安全节点。该节点之后的波次进度、经验与掉落会回退，已保存的长期进度保留。此局未结算的研究点仍随最近节点保留，开启另一局会放弃它们。',detail:'最近节点：'+describeSave(saveRef.current),confirm:'确认返回山门',footnote:'返回只结束本页战斗；磁盘上的最近节点与长期进度不会被改写。',run:leave});}else leave();
 }
 useEffect(()=>{
  try{vaultRef.current=new SaveVault(localStorage);const value=vaultRef.current.load();setSaved(value);refreshRecovery();if(value.keymap)setKeymap({...DEFAULT_KEYS,...value.keymap});}catch(error){refreshRecovery();saveFault(error);}
  let alive=true;loadArt().then(a=>{if(!alive)return;setArt(a);artRef.current=a;const r=new Renderer(canvasRef.current,a);rendererRef.current=r;setReady(true);}).catch(e=>setError(e.message));
  soundRef.current=new Sound();const keys=new Set();heldKeysRef.current=keys;
  const down=e=>{
   // Keys that belong to an IME composition (including Esc cancelling a candidate) stay with the text field.
   if(e.isComposing||e.keyCode===229)return;
   // macOS withholds keyup for other keys while Command is held; drop held movement so it cannot stick.
   if(e.key==='Meta'||e.metaKey)keys.clear();
   setInputDevice('keyboard');
   if(e.repeat&&e.code==='Escape'){e.preventDefault();e.stopImmediatePropagation();return;}
   if(hudSummaryRef.current){if(e.code==='Escape'){e.preventDefault();e.stopImmediatePropagation();hudSummaryRef.current=false;setHudSummary(false);}return;}
   if(practiceOfferRef.current){if(e.code==='Escape'){e.preventDefault();e.stopImmediatePropagation();setPracticeOffer(null);}return;}
   if(riskRef.current){if(e.code==='Escape'){e.preventDefault();e.stopImmediatePropagation();cancelRisk();}return;}if(helpRef.current){if(e.code==='Escape'){e.preventDefault();e.stopImmediatePropagation();closeHelp();}return;}
   if(resultRecordsRef.current){if(e.code==='Escape'){e.preventDefault();e.stopImmediatePropagation();resultRecordsRef.current=false;setResultRecords(false);}return;}
   if(bindRef.current&&pageRef.current==='settings'){e.preventDefault();if(e.code==='Escape'){e.stopImmediatePropagation();cancelBinding();message('已取消改键，原键位保留');return;}const problem=bindingError(e.code);if(problem){message(problem);return;}if(e.ctrlKey||e.altKey||e.metaKey){message('请单独按下新键，不使用组合键');return;}if(Object.entries(keyRef.current).some(([id,k])=>id!==bindRef.current&&k===e.code)){message('此键已用于另一项操作');return;}const action=bindRef.current,next={...keyRef.current,[action]:e.code};if(persist(s=>({...s,keymap:next}))){cancelBinding();message(({dash:'闪避',thunder:'辟邪神雷',formation:'御剑战术',item1:'物资一',item2:'物资二'}[action]||'操作')+'已改为 '+keyLabel(e.code));}return;}
   if(pageRef.current==='settings'){if(e.code==='Escape'){e.preventDefault();e.stopImmediatePropagation();closeSettings();}return;}
   if(runtimeFaultRef.current||pageRef.current!=='play')return;
   if(['INPUT','TEXTAREA'].includes(document.activeElement?.tagName)||e.metaKey||e.ctrlKey||e.altKey)return;
   const b=battleRef.current;if(!b)return;keys.add(e.code);
   if(e.code==='Escape'){e.preventDefault();e.stopImmediatePropagation();if(b.modeState==='battle')b.pause();else if(b.modeState==='pause')b.resume();else if(b.modeState==='choice')message('战斗已暂停 · 请先选定一项悟道，再继续历练');return;}
   if(b.modeState==='pause'&&['Space','Enter'].includes(e.code)&&(blockedChoiceKeys.current.has(e.code)||!document.activeElement?.closest('.scene-pause button,.scene-pause summary'))){e.preventDefault();e.stopImmediatePropagation();return;}
   if(['choice','cinematic'].includes(b.scene)&&['Space','Enter'].includes(e.code)&&(e.repeat||blockedChoiceKeys.current.has(e.code)||!document.activeElement?.closest('.scene-action,.scene-cinematic summary'))){e.preventDefault();e.stopImmediatePropagation();return;}
   if(b.modeState!=='battle'||e.repeat)return;if(Object.values(keyRef.current).includes(e.code))e.preventDefault();
   if(e.code===keyRef.current.dash){e.preventDefault();b.requestDash();}if(e.code===keyRef.current.thunder)b.thunder();if(e.code===keyRef.current.formation)b.changeFormation();
   if(e.code===keyRef.current.item1)b.consume(0);if(e.code===keyRef.current.item2)b.consume(1);
  };
  const up=e=>{if(e.key==='Meta')keys.clear();keys.delete(e.code);if(blockedChoiceKeys.current.delete(e.code)){e.preventDefault();e.stopImmediatePropagation();}};
  const blur=()=>{keys.clear();blockedChoiceKeys.current.clear();joy.current={x:0,y:0};const b=battleRef.current;clearAim();b?.pause();};
  const visibility=()=>{if(document.hidden)blur();};const resize=()=>rendererRef.current?.resize();
  const canvasObserver=typeof ResizeObserver==='function'?new ResizeObserver(()=>{if(alive)try{resize();}catch(error){runtimeFailure(error);}}):null;if(canvasRef.current)canvasObserver?.observe(canvasRef.current);
  const gate=sceneInput.current,listeners={pointerdown:e=>gate.pointerDown(e),pointermove:e=>gate.pointerMove(e),pointerup:e=>gate.pointerUp(e),pointercancel:e=>gate.pointerCancel(e),keydown:e=>gate.keyDown(e),keyup:e=>gate.keyUp(e),blur:e=>{if(e.target===window)gate.reset();}};for(const [name,handler]of Object.entries(listeners))window.addEventListener(name,handler,true);
  window.addEventListener('keydown',down,true);window.addEventListener('keyup',up,true);window.addEventListener('blur',blur);window.addEventListener('resize',resize);document.addEventListener('visibilitychange',visibility);
  const beforeLeave=e=>{if(runtimeFaultRef.current||settingsDirtyRef.current||checkpointDirty(battleRef.current,saveRef.current)||pendingSaveRef.current){e.preventDefault();e.returnValue='';}};
  const onStorage=e=>{if(studyRun(battleRef.current)){if(e.key===SAVE_KEY){battleRef.current.pause();message('另一窗口更新了正式记录；观察保持独立，结束后再核对。');}return;}if(e.key===SAVE_KEY&&!conflictRef.current&&vaultRef.current?.changedElsewhere()){saveFault({code:'conflict'});}};
  window.addEventListener('beforeunload',beforeLeave);window.addEventListener('storage',onStorage);
  let handle,last=performance.now(),elapsed=0;
  const frame=now=>{
   if(!alive)return;const raw=(now-last)/1000;last=now;elapsed+=Math.min(raw,MAX_FRAME);const b=battleRef.current,s=saveRef.current.settings;
   try{if(!runtimeFaultRef.current){
   if(b){b.input.x=(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0)+joy.current.x;b.input.y=(keys.has('KeyS')||keys.has('ArrowDown')?1:0)-(keys.has('KeyW')||keys.has('ArrowUp')?1:0)+joy.current.y;b.options.settings=s;b.accountCleared=saveRef.current.wins>0;stepBattle(b,raw);}
   const stick=mainRef.current?.querySelector('.touch-joystick span');if(stick){const length=Math.max(1,Math.hypot(joy.current.x,joy.current.y));stick.style.transform='translate('+joy.current.x/length*30+'px,'+joy.current.y/length*30+'px)';}rendererRef.current?.draw(b,b?.time||elapsed,s);soundRef.current.configure(s);soundRef.current.setPaused(document.hidden||!!riskRef.current||!!helpRef.current||!!b&&b.modeState!=='battle');if(!document.hidden&&(!b||b.modeState==='battle'))soundRef.current.update(elapsed,!!b?.boss);
   }}catch(error){runtimeFailure(error);}finally{if(alive)handle=requestAnimationFrame(frame);}
  };handle=requestAnimationFrame(frame);
  if(new URLSearchParams(location.search).has('test'))window.__FANREN__={loadArt,get sceneInput(){return sceneInput.current;},get sound(){return soundRef.current;},get camera(){return rendererRef.current?.camera;},get bossDirection(){return rendererRef.current?.bossDirection;},get battle(){return battleRef.current;},get save(){return saveRef.current;},get art(){return artRef.current;},get risk(){return riskRef.current;},get runtimeFault(){return runtimeFaultRef.current;},start:(o)=>startRef.current(o),home,step:n=>{for(let i=0;i<n;i++)battleRef.current?.update(1/60);redraw(v=>v+1);},render:()=>rendererRef.current?.draw(battleRef.current,battleRef.current?.time||0,saveRef.current.settings)};
  return()=>{for(const [name,handler]of Object.entries(listeners))window.removeEventListener(name,handler,true);canvasObserver?.disconnect();window.removeEventListener('beforeunload',beforeLeave);window.removeEventListener('storage',onStorage);alive=false;cancelAnimationFrame(handle);clearTimeout(sceneTimer.current);clearTimeout(toastTimer.current);soundRef.current?.close();window.removeEventListener('keydown',down,true);window.removeEventListener('keyup',up,true);window.removeEventListener('blur',blur);window.removeEventListener('resize',resize);document.removeEventListener('visibilitychange',visibility);delete window.__FANREN__;};
 },[]);
 function downloadText(raw,name){const blob=new Blob([raw||''],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 function exportSave(){let raw;if(vaultRef.current?.corrupt)raw=vaultRef.current.expectedRaw;else raw=JSON.stringify(pendingSaveRef.current?.next||saveRef.current,null,2);downloadText(raw,vaultRef.current?.corrupt?'青竹剑阵_原始存档.json':'青竹剑阵_存档.json');message('已发起备份下载，请确认文件已保存');}
 async function importSave(e){
  const file=e.target.files?.[0];if(!file)return;
  try{if(file.size>MAX_SAVE_IMPORT_BYTES)throw Error('恢复资料超过 8 MiB');const sourceRaw=await file.text(),candidates=recoveryImportCandidates(sourceRaw),expectedSnapshot=vaultRef.current.snapshot();setImportCandidates(candidates.map(c=>({...c,sourceRaw,expectedSnapshot})));message(candidates.some(c=>c.save)?'已生成只读预览，请选择记录后确认恢复':candidates.length?'原文未通过校验，仅能导出；当前记录未改变':'恢复包内没有可读取的原文');
  }catch(error){message('无法读取此存档：'+readableSaveError(error)+'。当前记录未被更改');}e.target.value='';
 }

 function unlockMeta(m){const s=saveRef.current;if(needsCultivationUpgrade(s)){upgradeCultivation();return;}if(s.meta.includes(m.id)||s.insight<m.cost)return;if(m.step>0&&!s.meta.includes(PATHS[m.path].id+'-meta-'+(m.step-1))){message('请先完成前一个修持节点');return;}persist(v=>({...v,metaRulesVersion:3,insight:v.insight-m.cost,meta:[...v.meta,m.id]}));soundRef.current?.play('choose');}
 function upgradeCultivation(after){const plan=planCultivationUpgrade(saveRef.current);showRisk({title:'启用新版洞府修持？',description:'循息引流、轻墨遁符、群息回养的触发与收益已调整，其他节点保留。确认后撤回旧树并全额返还 '+plan.refund+' 点心得，可自由分配新节点。已有续玩仍使用出发时的旧配置，章节、成就、战绩与药园保留。',detail:plan.nodes.map(m=>m.name).join('、')||'无需返还的旧节点',confirm:'确认返还并启用新版',run:()=>persist(v=>planCultivationUpgrade(v).save,{backup:true,onSuccess:()=>{message('旧修持已全额返还，新版六路专修已开放');after?.();}}),resumeOnCancel:false});}
 function refundMeta(path=null,fromStep=0){const plan=planMetaRefund(saveRef.current,{path,fromStep});if(!plan.nodes.length)return;
  const title=path===null?'重置全部洞府修持？':fromStep===0?'重置'+PATHS[path].name+'分支？':'撤回「'+plan.nodes[0].name+'」及后续修持？';
  showRisk({title,description:'将撤回所列修持，全额返还 '+plan.refund+' 点修炼心得，之后可以重新分配。当前续玩仍使用出发时的修持配置，改动从下一局生效；章节、成就和其他进度保留。',detail:plan.nodes.map(m=>m.name).join('、'),confirm:'确认撤回并返还心得',run:()=>persist(v=>planMetaRefund(v,{path,fromStep}).save,{backup:true,onSuccess:()=>message('已返还 '+plan.refund+' 点心得，可重新分配修持')}),resumeOnCancel:false});
 }
 function refundGarden(){const plan=planGardenRefund(saveRef.current);if(!plan.refund)return;showRisk({title:'重置药园研究？',description:'返还已研究方案消耗的 '+plan.refund+' 点研究点，保留默认补给「稳行温养」。可以立即改研其他方案；本次续玩的出发补给不受影响。',detail:'已结算研究与同局领取凭据保留，重置不会重复领取历练奖励。',confirm:'确认重置并返还研究点',run:()=>persist(v=>planGardenRefund(v).save,{backup:true,onSuccess:()=>message('药园研究已重置，研究点已返还')}),resumeOnCancel:false});}
 const b=runtimeFault?null:battleRef.current,p=b?.player,current=b?.chapterInfo||CHAPTERS[b?.chapter||0],isPlay=page==='play',hasBoss=Boolean(b?.boss),achievements=achievementList(save),thunder=b?.thunderReadiness();
 const sceneTitles={intermission:'秘境整备',cinematic:'仙途纪事',intro:b?.mode==='training'?(b.options.guidedPractice?'试剑台 · 分步操作练习':'试剑台 · 自由试招'):current.name,choice:'临战悟道',shop:'整理行囊',event:EVENTS[b?.eventIndex||0].name,pause:'暂歇片刻',chapterEnd:'此境已过',result:b?.won?'携宝而归':'此行止步'};
 function combatAction(action){if(battleRef.current?.modeState==='battle'&&!riskRef.current&&!helpRef.current&&!runtimeFaultRef.current)action();}
 function equipmentChange(index,action,replacement=null){
  const run=battleRef.current,core=CORES.find(c=>c.id===run?.relics[index]);
  const apply=()=>{if(run!==battleRef.current)return;checkpointBackupRef.current=!!core;try{action();redraw(v=>v+1);}finally{checkpointBackupRef.current=false;}};
  if(!core){apply();return;}
  showRisk({kind:'equipment',title:(replacement?'替换':'卸下')+'核心「'+core.name+'」？',description:'这会立即移除此核心及其战术效果，并保存当前整备。免费核心不返还灵石；之后能否再取得取决于后续核心选项。',detail:replacement?'将购入「'+replacement.name+'」，花费 '+replacement.price+' 灵石；共享携行位仍为六格。':'本次回收返还 0 灵石，空出一个携行位置。',confirm:replacement?'确认替换核心':'确认卸下核心',run:apply});
 }
 function confirmRestDeparture(){const run=battleRef.current;if(!run?.rest||!run.restReadiness().ready||riskRef.current||conflictRef.current)return;const choice=run.rest.coreSelection,old=CORES.find(c=>c.id===choice?.replaceId);if(!old||run.rest.coreApplied||run.queuedChoices){run.continueRest();return;}const next=CORES.find(c=>c.id===choice.id),selection=JSON.stringify(choice);showRisk({kind:'equipment',title:'出发并替换核心？',description:'将换下「'+old.name+'」，装配「'+next.name+'」。旧核心及其战术效果会移除，免费核心不返还灵石；同时结算本次暂选机缘并出发。',detail:'确认前保留原核心；确认时备份当前整备，取消可继续改选。',confirm:'确认替换并出发',resumeOnCancel:false,run:()=>{if(run!==battleRef.current||conflictRef.current||JSON.stringify(run.rest?.coreSelection)!==selection)return;checkpointBackupRef.current=true;try{run.continueRest();}finally{checkpointBackupRef.current=false;}}});}
 function replaceItem(shopIndex,index){const run=battleRef.current;const apply=()=>{if(run.buy(shopIndex,index)===true)setReplace(null);};if(run.shop[shopIndex]?.kind==='relic')equipmentChange(index,apply,run.shop[shopIndex]);else apply();}
 function sellItem(index){const run=battleRef.current;equipmentChange(index,()=>run.sell(index));}
 useLayoutEffect(()=>{if(['choice','pause'].includes(scene)&&!risk&&!help)choiceFocusRef.current?.focus({preventScroll:true});},[scene,b?.choices,risk,help]);
 function buyItem(index){const result=b.buy(index);if(result==='replace'||result==='slots')setReplace(index);redraw(v=>v+1);}
 useLayoutEffect(()=>{const main=mainRef.current;if(!ready||!isPlay||!main)return;let last='';const measure=()=>{const rect=main.getBoundingClientRect(),key=[rect.width,rect.height,b?.boss?.name,b?.objective?.kind].join(':');if(last===key)return;last=key;
  // Measure the uncompressed layout in an inert copy so compression never changes
  // its own entry/exit test. Only viewport/major HUD changes rebuild this probe.
  const probe=document.createElement('div');probe.className=main.className.replace('hud-compact','');probe.setAttribute('aria-hidden','true');probe.inert=true;Object.assign(probe.style,{position:'fixed',left:'-10000px',top:'0',right:'auto',bottom:'auto',width:rect.width+'px',height:rect.height+'px',visibility:'hidden'});
  for(const selector of ['.battle-header','.battle-footer','.mobile-status','.boss-bar','.objective-note']){const node=main.querySelector(selector);if(node)probe.append(node.cloneNode(true));}document.body.append(probe);let top=0;for(const node of probe.querySelectorAll('.battle-header,.mobile-status,.boss-bar,.objective-note')){const r=node.getBoundingClientRect();if(r.height&&r.bottom<rect.height*.6)top=Math.max(top,r.bottom);}const bottom=probe.querySelector('.battle-footer')?.getBoundingClientRect().height||0;probe.remove();const available=rect.height-top-bottom-16,target=rect.height<=420?rect.height*.4:Math.max(220,rect.height*.35);
  // Round-2 C-2: on a narrow portrait phone the roomy HUD leaves the battle band under half the viewport, so the compact HUD
  // (one status row, summary button, 44px controls) takes over until the band would keep at least 55% of the height.
  const portraitPhone=rect.width<=430&&rect.height>rect.width,need=portraitPhone?Math.max(target+32,rect.height*.55):target+32;
  setCompactHUD(previous=>available<need||previous&&available<need+32);
 };measure();const observer=new ResizeObserver(measure);observer.observe(main);return()=>observer.disconnect();},[ready,isPlay,b?.boss?.name,b?.objective?.kind,inputDevice]);
 useLayoutEffect(()=>{const f=footerRef.current,header=headerRef.current;if(!f||!header)return;const measure=()=>{const height=f.getBoundingClientRect().height;mainRef.current?.style.setProperty('--battle-footer-height',height+'px');const main=mainRef.current.getBoundingClientRect();let top=header.getBoundingClientRect().bottom-main.top;mainRef.current.style.setProperty('--battle-header-base',top+'px');mainRef.current.style.setProperty('--battle-header-height',top+'px');for(const node of mainRef.current.querySelectorAll('.wave-status,.boss-bar,.mobile-status,.objective-note,.practice-panel')){const r=node.getBoundingClientRect();if(node.classList.contains('practice-panel')&&(main.width>600||main.height<=420))continue;if(r.height&&getComputedStyle(node).top!=='auto'&&r.bottom-main.top<main.height*.6)top=Math.max(top,r.bottom-main.top);}const stick=mainRef.current.querySelector('.touch-joystick')?.getBoundingClientRect();if(stick?.width){mainRef.current.style.setProperty('--touch-occupied',(stick.width+84)+'px');const right=touchSettings(save.settings).joystickSide==='right';mainRef.current.style.setProperty('--thumb-left',Math.max(4,Math.min(main.width-48,(right?stick.left-50:stick.right+6)-main.left))+'px');mainRef.current.style.setProperty('--thumb-top',Math.max(top,stick.bottom-main.top-44)+'px');}mainRef.current.style.setProperty('--battle-feedback-height',(mainRef.current.querySelector('.combat-feedback')?.getBoundingClientRect().height||0)+'px');const band=main.height-top-height-16;setSpaceLimited(band<(main.height<=420?main.height*.4:Math.max(220,main.height*.35)));if(rendererRef.current){rendererRef.current.hudBottom=height;rendererRef.current.hudTop=top;const side=mainRef.current.querySelector('.battle-side')?.getBoundingClientRect();const css=getComputedStyle(mainRef.current),safeLeft=parseFloat(css.getPropertyValue('--game-safe-left'))||0,safeRight=parseFloat(css.getPropertyValue('--game-safe-right'))||0;rendererRef.current.hudLeft=side?.width?side.right-main.left:safeLeft;rendererRef.current.hudRight=safeRight;rendererRef.current.hudAvoid=[...mainRef.current.querySelectorAll('.game-toast,.practice-panel,.touch-joystick,.thumb-clear,.combat-feedback,.objective-note')].map(n=>n.getBoundingClientRect()).filter(r=>r.width&&r.height).map(r=>({left:r.left-main.left,right:r.right-main.left,top:r.top-main.top,bottom:r.bottom-main.top}));}};measure();const observer=new ResizeObserver(measure);observer.observe(f);observer.observe(header);for(const node of mainRef.current.querySelectorAll('.wave-status,.boss-bar,.mobile-status,.objective-note,.battle-side,.practice-panel,.combat-feedback'))observer.observe(node);return()=>observer.disconnect();},[ready,isPlay,runtimeFault,hasBoss,b?.chapter,b?.wave,b?.practice?.step,save.settings,b?.input.touchAim,toast,compactHUD]);
 return <main onPointerDownCapture={e=>setInputDevice(e.pointerType==='touch'?'touch':'keyboard')} ref={mainRef} className={'fanren '+(compactHUD?'hud-compact ':'')+(spaceLimited?'space-limited ':'')+(scene?'scene-covered ':'')+'page-'+page+' '+(isPlay?'in-battle':'in-menu')+' input-'+inputDevice+' touch-joystick-'+touchSettings(save.settings).joystickSide+' joystick-'+touchSettings(save.settings).joystickSize+' touch-skills-'+touchSettings(save.settings).skillSide}>
  <canvas ref={canvasRef} className="world-canvas" aria-label="韩立御剑战斗场地" tabIndex={isPlay?0:-1}
   onPointerMove={e=>{if(!b||b.modeState!=='battle'||risk||help)return;const point=rendererRef.current?.toWorld(e.clientX,e.clientY);if(e.pointerType==='touch'&&aimPointer.current===e.pointerId){if(aimStart.current&&Math.hypot(e.clientX-aimStart.current.x,e.clientY-aimStart.current.y)>8)aimStart.current.dragged=true;if(aimStart.current?.dragged)setTouchAim(b,point,{allowLock:false});else if(b.touchLockId==null)b.input.aim=point;}else if(e.pointerType!=='touch'&&!b.input.touchAim)b.input.aim=point;}}
   onPointerDown={e=>{if(!b||b.modeState!=='battle'||risk||help||e.pointerType!=='touch'&&e.button!==0||aimPointer.current!==null||!capturePointer(e))return;e.preventDefault();aimPointer.current=e.pointerId;aimStart.current={x:e.clientX,y:e.clientY,dragged:false};const point=rendererRef.current?.toWorld(e.clientX,e.clientY);if(e.pointerType==='touch')setTouchAim(b,point,{scale:rendererRef.current?.camera.scale});else{clearTouchLock(b);b.input.focus=true;b.input.touchAim=false;b.input.aim=point;}redraw(v=>v+1);}}
   onPointerUp={e=>{if(aimPointer.current!==e.pointerId)return;aimPointer.current=null;aimStart.current=null;if(b&&!b.input.touchAim){practiceFocusRelease(b);b.input.focus=false;redraw(v=>v+1);}}} onPointerCancel={e=>{if(aimPointer.current===e.pointerId)clearAim();}} onLostPointerCapture={e=>{if(aimPointer.current===e.pointerId)clearAim();}} onContextMenu={e=>e.preventDefault()}/>
  {!ready&&<div className="loading-screen"><div className="seal">凡</div><h1>青竹剑阵</h1><p>{error||'正在收拢飞剑…'}</p>{error&&<><Btn onClick={()=>location.reload()}>重新载入</Btn><Btn variant="outline" onClick={exportSave} disabled={vaultRef.current?.expectedRaw===undefined}>导出存档</Btn><p>若浏览器无法解码资源，可使用同功能的 PNG 资源兼容版；原存档不会因图片加载失败而清空。</p>{location.protocol==='file:'&&compatibilityEntry(location.pathname)&&<Btn variant="outline" onClick={()=>location.assign(new URL(compatibilityEntry(location.pathname),location.href).href)}>打开 PNG 兼容版</Btn>}</>}</div>}
  {ready&&!isPlay&&<>
   <header className="menu-header"><div className="brand"><span className="seal">凡</span><div>凡人修仙传<small>青竹剑阵 · {GAME_ARC} · {GAME_VERSION}</small></div></div><div className="header-actions"><button className={'save-state '+(['error','conflict','recovery'].includes(saveStatus)?'save-warning':'')} onClick={()=>{if(studyRun(battleRef.current)){message('观察期间不处理正式保存；请先结束观察。');return;}if(pendingSaveRef.current)saveFault({code:saveStatus==='conflict'?'conflict':'storage',message:'最近一次保存未完成'},pendingSaveRef.current.next,pendingSaveRef.current.options);else openSettings();}}><span className="online-dot"/>{saveStatus==='recovery'?'恢复记录待处理':saveStatus==='error'?'保存需处理':saveStatus==='conflict'?'发现存档冲突':save.savedAt?'已保存 '+new Date(save.savedAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):'本地记录就绪'}</button><Btn variant="ghost" onClick={()=>page==='settings'?closeSettings():openSettings()} aria-label="设置">⚙</Btn></div></header>
   {page==='home'?<>
    <section className={'title-panel '+(save.checkpoint?'has-checkpoint':'')}><span className="eyebrow">{GAME_ARC} · 结丹初期</span><h1>青竹<span>剑阵</span></h1><div className="title-rule"/><p className="opening">七十二口青竹蜂云剑，已藏于身。<br/>于危局中寻生机，于剑光中问长生。</p>
     <RecoveryPanel compact issue={recoveryInfo.issue} candidates={recoveryInfo.candidates} onAdopt={adoptRecovery} onExport={exportRecovery}/><div className="start-actions">{recoveryInfo.issue?<><Btn className="primary-start" onClick={openSettings}>处理待恢复记录 →</Btn><Btn className="new-journey" variant="outline" onClick={preserveAndStart}>保留原文并开启新历练 <span>＋</span></Btn></>:save.checkpoint?<><Btn className="primary-start" onClick={continueSaved}>继续历练 <span>→</span></Btn><div className="checkpoint-caption">{describeSave(save)}<small>从最近安全节点继续</small></div><Btn className="new-journey" variant="outline" onClick={()=>setPage('journey')}>开启新历练 <span>＋</span></Btn></>:<Btn className="primary-start" onClick={()=>setPage('journey')}>踏入修仙路 <span>→</span></Btn>}</div>
     <div className="quick-nav"><Btn variant="ghost" onClick={openLodge}>洞府修持 <span>↗</span></Btn><Btn variant="ghost" onClick={()=>setPage('codex')}>藏经图鉴 <span>↗</span></Btn><Btn variant="ghost" onClick={()=>openHelp('guide')}>游玩说明 <span>↗</span></Btn><Btn variant="ghost" onClick={()=>openHelp('changes')}>更新日志 <span>↗</span></Btn><Btn variant="ghost" onClick={()=>openHelp('license')}>开源许可与源码 <span>↗</span></Btn></div>
     <div className="home-stats"><span><b>{recoveryInfo.issue?'—':save.best||1}</b>最高御剑</span><span><b>{recoveryInfo.issue?'待恢复':save.kills.toLocaleString()}</b>累计斩敌</span><span><b>{recoveryInfo.issue?'—':save.insight}</b>修炼心得</span></div>
    </section>
    <div className="scene-caption"><span>一剑入道 · 万里归途</span><small>青竹蜂云剑</small></div>
    <div className="chapter-rail">{MENU_CHAPTERS.map((c,i)=><button key={c.id} className={'chapter-tile '+(i===(save.checkpoint?.chapter??save.unlocked)?'active':'')+(i>save.unlocked?' locked':'')} onClick={()=>{if(i>save.unlocked){message('先完成 '+chapterName(i-1)+'，再探此境');return;}setChapter(i);setMode('replay');setPage('journey');}} style={{'--chapter-color':c.color}}><span className="chapter-number">{c.tag}</span><div><small>{i>save.unlocked?'未历之境':(save.completed||[]).includes(i)?'已通关 · 可重温':save.checkpoint?.chapter===i?'当前历练':c.sub}</small><strong>{c.name}</strong></div><span className="chapter-status">{i>save.unlocked?'◇':'↗'}</span></button>)}</div>
    <footer className="menu-footer"><span className="creator-credit">制作人：bilibili@卡布奇诺ultra</span><span>自动御剑 · {keyLabel(keymap.dash)}闪避 · {keyLabel(keymap.thunder)} 神雷</span></footer>
   </>:<section className="library-panel">
    <div className="panel-top"><div><span className="eyebrow">青竹剑阵 / {page==='journey'?'历练':page==='lodge'?'洞府':page==='codex'?'藏经阁':'设置'}</span><h2>{page==='journey'?'选择此行':page==='lodge'?'洞府修持':page==='codex'?'藏经图鉴':'音画与操控'}</h2></div><Btn variant="outline" onClick={()=>page==='settings'?closeSettings():setPage(page==='lodge'?lodgeOrigin.current:'home')}>{page==='settings'&&settingsOrigin.current==='play'?'返回暂停':page==='lodge'&&lodgeOrigin.current==='journey'?'返回出发配置':'返回山门'}</Btn></div>
    {page==='journey'&&<div className="journey-frame"><PanelBody><div className="journey-grid"><div>
     <h3>选定此行的战术侧重</h3><p className="muted">六种起手，同样御使七十二剑。选择后查看演示与操作要点。</p><div className="path-grid">{PATHS.map((v,i)=><button className={'path-card '+(path===i?'selected':'')} key={v.id} onClick={()=>setPath(i)} style={{'--path-color':v.color}}><span className="path-top"><span className="path-icon">{v.icon}</span><b>{v.name}</b></span><strong>{STARTERS[i].tag}</strong><small>{STARTERS[i].role}</small><small className="starter-complexity">{['指挥飞剑 · 易上手','规划施雷 · 需熟悉资源','移动与驻定 · 需练习','协战追猎 · 易上手','留符引敌 · 需练习','护盾与化解 · 需练习'][i]}</small><em>{starterDetails(i,save).initial}</em></button>)}</div>
     <h3>历练方式</h3><div className="mode-row">{[['story','原著主篇'],['endless','无尽挑战'],['seed','定种历练'],['replay','章回重温']].map(([id,label])=><Btn key={id} variant="outline" className={mode===id?'selected':''} aria-pressed={mode===id} disabled={id==='endless'&&save.wins<=0} onClick={()=>setMode(id)}>{label}</Btn>)}</div>
     <p className="mode-explanation">{{story:'六章共22节点。结算心得、章节与药园研究；完整胜局可按净战斗时间入榜。',endless:'主篇或完整定种胜局后开放新局。循环挑战，结算心得与击杀，不发章节解锁和药园研究；按已完成圈次排名。已有无尽续玩不受门槛影响。',seed:'输入种子重现路线。心得、章节和药园研究与主篇相同；完整22节点胜局单独分组排名，也开放无尽。',replay:'从已解锁章节开始重温。结算心得与击杀，不发章节解锁或药园研究，不进入最佳时间排名。'}[mode]}</p>{save.wins<=0&&<p className="muted">无尽新局：完成一次主篇或完整定种胜局后开放。</p>}
     {mode==='seed'&&<label className="field-label">历练种子<input value={seed} onChange={e=>setSeed(printableText(e.target.value))} placeholder="相同种子、相同选择，重现同一局" maxLength={60}/></label>}
     {mode==='replay'&&<div className="mode-row">{MENU_CHAPTERS.map(c=><Btn key={c.id} variant="outline" disabled={c.id>save.unlocked} className={chapter===c.id?'selected':''} onClick={()=>setChapter(c.id)}>{c.name}</Btn>)}</div>}
    <Btn className="journey-lodge" variant="outline" onClick={openLodge}>前往洞府修持与药园 →</Btn><p className="muted">往返保留此行起手、难度、方式、种子与补给；当前续玩仍沿用原出发配置。</p><SupplyChooser save={save} onChange={garden=>persist(s=>({...s,garden}))}/></div><aside className="journey-aside"><div className="starter-heading"><Chip color={PATHS[path].color}>{PATHS[path].name}</Chip><h3>{STARTERS[path].tag}</h3></div><StarterPreview art={art} path={path}/><p className="starter-action">{starterDetails(path,save).action}</p><p className="starter-limit">留意：{starterDetails(path,save).limit}</p><CultivationSummary options={{meta:save.meta,metaRulesVersion:save.metaRulesVersion}} path={path} legacy={needsCultivationUpgrade(save)}/><h3>险境难度</h3>{DIFFICULTIES.map((v,i)=><button className={'difficulty-option '+(difficulty===i?'selected':'')} key={v.name} onClick={()=>setDifficulty(i)}><strong>{v.name}</strong><small>{v.desc}</small></button>)}<p className="difficulty-guidance">{DIFFICULTY_GUIDANCE[difficulty]}</p><p className="difficulty-summary">{DIFFICULTIES[difficulty].desc}。起手与修持另计；新秘境经验按节点分配，三档不使用击杀经验倍率。基础悟道重选2次，修持及机缘另计。</p></aside></div></PanelBody><div className="journey-launch"><div className="launch-selection"><strong>当前起手：{PATHS[path].name}</strong><label>当前难度：<select aria-label="当前难度" value={difficulty} onChange={e=>setDifficulty(Number(e.target.value))}>{DIFFICULTIES.map((d,i)=><option value={i} key={d.name}>{d.name} · {DIFFICULTY_GUIDANCE[i].split(' · ')[0]}</option>)}</select></label></div><Btn className="primary-start" onClick={()=>start()}>启程 <span>→</span></Btn><Btn variant="outline" onClick={()=>start({mode:'training'})}>试剑台 · 自由试招</Btn><details className="study-entry"><summary>前两章 · 雷法／符阵对照体验</summary><p>固定同种子、标准难度、空修持；真实前两章。各玩一次，记录起点留符、命中/阻挡与收益；只导出观察包，不写正式进度。</p><Btn variant="outline" onClick={()=>start(studyOptions(1))}>雷法对照体验</Btn><Btn variant="outline" onClick={()=>start(studyOptions(4))}>符阵对照体验</Btn><label>恢复观察包<input type="file" accept=".json" aria-label="恢复观察包" onChange={importObservation}/></label></details><Btn variant="outline" onClick={()=>{practiceReturn.current={path,difficulty,mode,seed,chapter};start({mode:'training',guidedPractice:true});}}>分步操作练习</Btn></div></div>}
    {page==='lodge'&&<><nav className="lodge-nav"><button onClick={()=>document.getElementById('lodge-cultivation')?.scrollIntoView({block:'start'})}>六路修持 ↓</button><button onClick={()=>document.getElementById('lodge-garden')?.scrollIntoView({block:'start'})}>洞府药园 ↓</button></nav><div id="lodge-cultivation"><CultivationPanel path={lodgeOrigin.current==='journey'?path:save.checkpoint?.options?.path??path} save={save} onUnlock={unlockMeta} onRefund={refundMeta} onUpgrade={()=>upgradeCultivation()}/></div><div id="lodge-garden"><Garden save={save} art={art} onChange={garden=>persist(s=>({...s,garden}))} onReset={refundGarden}/></div></>}
    {page==='codex'&&<Tabs value={codex} onValueChange={setCodex}><TabsList className="codex-tabs">{[['records','历练成绩'],['traits','战术修持 · 72'],['relics','器物与配置 · 48'],['enemies','敌情 · '+ENEMIES.length],['combos','流派联动 · 12'],['consumables','行囊 · 18'],['story','原著纪事'],['achievements','成就 · 40']].map(([id,label])=><TabsTrigger key={id} value={id}>{label}</TabsTrigger>)}</TabsList>
     <TabsContent value="records"><RecordsPanel save={save}/></TabsContent><TabsContent value="traits"><p className="muted">以下按当前新局基础规则展示战术强化，并非新增的原著功法；旧局以本局面板为准。数值强化最多三次，独立效果修持一次。</p><div className="codex-grid">{TRAITS.map(t=><article className="codex-card" key={t.id}><Chip color={PATHS[t.path].color}>{PATHS[t.path].name}</Chip><h3>{t.name}</h3><p>{traitText({rulesVersion:3,options:{balanceVersion:BALANCE_VERSION}},t)}</p></article>)}</div></TabsContent>
     <TabsContent value="relics"><div className="codex-grid">{EQUIPMENT.map(r=><article className="codex-card" key={r.id}><Chip>{r.core?'战术核心':r.story?'原著器物 / 协战':'携行战术'}</Chip>{r.core&&<AtlasSprite art={art} index={r.icon}/>}<h3>{r.name}</h3><p>{r.core?coreDescription(r):modText(r.mods)}</p><small>{r.core?'当前新局基础规则 · '+r.requirement:r.source}</small></article>)}</div></TabsContent>
     <TabsContent value="enemies"><p className="muted">以当期敌情为基础设计的战斗行为；普通行为名称不作为新增原著物种。</p><div className="codex-grid">{ENEMIES.map(e=><article className="codex-card enemy-card" key={e.id}><SpriteView art={art} enemy index={e.sprite} height={60}/><div><Chip>{e.family} · 普通兵种</Chip><h3>{e.name}</h3><p>{e.desc}</p></div></article>)}</div></TabsContent>
     <TabsContent value="combos"><div className="codex-grid">{COMBOS.map(c=><article className="codex-card" key={c.name}><Chip>{PATHS.find(p=>p.id===c.a).name} × {PATHS.find(p=>p.id===c.b).name}</Chip><h3>{c.name}</h3><p>{comboDescription(c,save.checkpoint)}</p><small>两个方向各选 3 种不同强化后激活</small></article>)}</div></TabsContent>
     <TabsContent value="consumables"><div className="codex-grid">{CONSUMABLES.map(c=><article className="codex-card" key={c.id}><Chip>游戏化携行物资</Chip><h3>{c.name}</h3><p>{c.desc}</p></article>)}</div></TabsContent>
     <TabsContent value="story"><StoryReplay art={art} save={save} gate={sceneInput.current}/><p className="muted">账号历史按历经章节展示；本局行囊与配置只读最近保存的续玩记录，暂选不算已配置。没有独立持有记录的封存物只作纪事，不补发器物。</p><div className="story-items">{STORY_ITEMS.map(item=>{const state=catalogItemState(item,save);return <article className="codex-card" key={item.id}><h3>{item.name}</h3><Chip>{state.history}</Chip>{item.canon===false&&<Chip>{item.canonNote||'游戏化设定'}</Chip>}<p>{state.inventory}<br/>{state.configuration}</p><p>{item.desc}</p></article>;})}</div><div className="story-layout"><div>{MENU_CHAPTERS.map(c=><details className="journal-chapter" key={c.id} open={c.id===0}><summary>{c.tag} · {c.name} <small>十则纪事</small></summary>{JOURNAL.filter(j=>j.chapter===c.id).map(j=><article className="journal-entry" key={j.id}><span>{String(j.id%10+1).padStart(2,'0')}</span><div><h3>{j.title}</h3><p>{j.text}</p></div></article>)}<small>依据：{c.source}；纪事为改编表达。</small></details>)}</div><aside><h3>剧情边界</h3><p>青竹蜂云剑已在乱星海炼成，局内每级多一剑是游戏规则。</p><p>大庚剑阵、风雷翅和后期神通不在本篇提前登场。</p><p>辟邪神雷有储量。玄骨终局保留修罗圣火失控的结局，不以无限雷击改写因果。</p><h3>原著章节参考</h3>{LORE_URLS.map(([name,url])=><a key={url} href={url} target="_blank" rel="noreferrer">{name} ↗</a>)}<small>参考链接需联网；游戏本身可离线运行。</small></aside></div></TabsContent>
     <TabsContent value="achievements"><p className="resource-line">{achievements.filter(a=>a.done).length} / 40 已完成</p><div className="codex-grid">{achievements.map(a=><article className={'codex-card '+(a.done?'achieved':'')} key={a.name}><Chip>{a.done?'已达成 ✓':'未达成 ◇'}</Chip><h3>{a.name}</h3><p>{a.desc}</p></article>)}</div></TabsContent>
    </Tabs>}
    {page==='settings'&&studyRun(b)&&<section className="study-settings-readonly"><h3>观察期间设置只读</h3><p>沿用进入观察前的设备设置。结束观察后再调整；正式主档、续玩、待保存结果、备份与保护资料保持。</p><fieldset disabled><TouchSettings settings={save.settings} b={b} active={true} onChange={()=>{}}/></fieldset></section>}{page==='settings'&&!studyRun(b)&&<><RecoveryPanel issue={recoveryInfo.issue} candidates={recoveryInfo.candidates} onAdopt={adoptRecovery} onExport={exportRecovery}/>{importCandidates.length>0&&<RecoveryPanel issue="导入资料 · 只读预览，尚未覆盖" candidates={importCandidates} onAdopt={adoptRecovery} onExport={()=>downloadText(JSON.stringify({format:'fanren-recovery-records',records:importCandidates.map(c=>({raw:c.raw,savedAt:0}))},null,2),'青竹剑阵_导入原文.json')}/>}<TouchSettings settings={save.settings} b={b} active={settingsOrigin.current==='play'} onChange={updateTouchSettings}/><div className="settings-grid"><section><h3>声音与画面</h3>{[['music','背景乐'],['sfx','音效']].map(([id,label])=><label className="slider-label" key={id}><span>{label}<small>{Math.round(save.settings[id]*100)}%</small></span><Slider aria-label={label} min={0} max={1} step={.05} value={[save.settings[id]]} onValueChange={v=>{soundRef.current?.start();previewSettings(id,Array.isArray(v)?v[0]:v);}} onValueCommitted={v=>updateSettings(id,Array.isArray(v)?v[0]:v)}/></label>)}{[['shake','受击震动'],['flash','神雷闪光'],['numbers','普通伤害数字'],['skipSeenCinematics','跳过本局已看过场'],['endlessSkipSeen','无尽第 2 圈起默认跳过已看过场'],['skipSeenAfterWin','通关后自动跳过纪事过场（账号级）']].map(([id,label])=><div className="toggle-line" key={id}><span>{label}</span><Btn variant="outline" onClick={()=>updateSettings(id,!save.settings[id])} aria-pressed={save.settings[id]!==false}>{save.settings[id]!==false?'开启':'关闭'}</Btn></div>)}<p className="setting-explanation">已看记录仅属于同一次历练，主要用于无尽后续圈及恢复；新开另一局重新记录。开启后也作用于当前或已恢复的叙事3历练；旧叙事1／2不启用。「无尽第 2 圈起默认跳过已看过场」只作用于无尽挑战 2 的新局：第 2 圈起本局已看过的过场自动跳过（默认开启，可在此关闭）；挑战 1／0 的旧无尽局仍按上一项设置。「通关后自动跳过纪事过场（账号级）」默认关闭：本账号已有通关记录时，叙事3历练的纪事过场自动跳过，仍按正式流程推进并记入本局已看；纪事可在图鉴重温。</p><div className="toggle-line"><span>飞剑尾迹</span><Btn variant="outline" onClick={()=>updateSettings('quality',save.settings.quality?0:1)}>{save.settings.quality?'完整':'精简'}</Btn></div></section>
     <section><h3>操作键位</h3><p className="muted">移动固定为 WASD / 方向键，Esc 暂停。改键时按 Esc 或离开设置可取消；不支持 Ctrl / Alt / Meta 单键或组合键。</p>{invalidBindings(keymap).length>0&&<output className="key-warning">当前有不可用或重复的键位，请逐项重新设置。旧绑定仍保留，未自动改写存档。</output>}{Object.entries({dash:'闪避',thunder:'辟邪神雷',formation:'御剑战术',item1:'物资一',item2:'物资二'}).map(([id,label])=><div className="toggle-line" key={id}><span>{label}</span><Btn variant="outline" onClick={()=>{bindRef.current=id;setBind(id);}}>{bind===id?'请按新按键…':keyLabel(keymap[id])}</Btn></div>)}<h3>本地存档</h3><div className="mode-row"><Btn variant="outline" onClick={exportSave}>导出存档</Btn><Btn variant="outline" onClick={restoreBackup}>恢复上次备份</Btn><Btn variant="outline" onClick={exportRecovery}>导出原始记录</Btn>{vaultRef.current?.corrupt&&<Btn variant="outline" onClick={restoreProfileOnly}>恢复长期进度</Btn>}{(count=>count>0&&<Btn variant="outline" onClick={clearIsolated}>清理隔离原文 · {count} 份</Btn>)(isolatedCount())}<label className="import-label">导入存档<input type="file" accept=".json,application/json" onChange={importSave}/></label></div><p className="muted">新局会保存节点、选路和悟道时的战场，旧局恢复最近整备节点；更换浏览器前可先导出。</p></section></div></>}
   </section>}
  </>}
  {ready&&isPlay&&b&&<>
   <header ref={headerRef} className="battle-header" onPointerDown={e=>e.stopPropagation()}><div className="hero-status"><div className="avatar-frame"><SpriteView art={art} height={55}/></div><div className="vitals"><div className="hero-name">韩立 <small>结丹初期</small></div><div className={'hp-track '+(p.hp/p.maxHp<.3?'low-health':'')}><span style={{width:percent(p.hp,p.maxHp)+'%'}}/><b>{Math.ceil(p.hp)} / {p.maxHp}</b></div><div className="shield-track"><span style={{width:percent(p.shield,Math.max(p.maxShield,1))+'%'}}/></div><div className="shield-value" title="当前护盾 / 常驻上限；额外护盾不会随时间衰减，仍会被伤害消耗">护盾 {Math.round(p.shield*10)/10} / {Math.round(p.maxShield*10)/10}{p.shield>p.maxShield&&<small aria-label="含额外护盾"> ＋</small>}</div></div></div>
    <div className="wave-status"><small>{current.tag} / {current.sub}</small><strong>{current.name}</strong><span>{b.mode==='training'?'自由训练 · 持续练习，不结算节点':b.isExpedition?'节点 '+(b.wave+1)+' / '+b.routes[b.chapter].length+' · '+objectiveGuidance(b):b.wave<3?'第 '+(b.wave+1)+' / 3 波 · '+Math.max(0,55-Math.floor(b.waveTime))+' 秒':current.objective}</span></div>
    <div className="battle-counters"><button className={'battle-save-chip '+(['error','conflict','recovery'].includes(saveStatus)?'save-warning':'')} aria-label="查看最近保存状态" title="暂停查看最近保存状态" onClick={()=>b.pause()}>◈</button><div><small>斩敌</small><strong>{b.kills}</strong></div><div><small>灵石</small><strong>{b.gold}</strong></div><div><small>历时</small><strong>{clock(elapsedBattle(b)??b.time)}</strong></div><CombatButton className={"touch-aim-clear "+(b.input.touchAim?"aim-active":"")+(b.input.touchAim&&b.defendAlertUntil>b.time?" defend-alert":"")} aria-label={b.input.touchAim?"解除触屏集火":"点按战场设置瞄准点"} disabled={!b.input.touchAim} onAction={()=>combatAction(releaseAim)}>{b.input.touchAim?"解除集火":"点按瞄准"}</CombatButton><CombatButton as={Btn} trigger="up" variant="outline" onAction={()=>b.pause()} aria-label="暂停">Ⅱ</CombatButton></div>
   </header>
   {invalidBindings(keymap).length>0&&<button className="battle-key-warning" onClick={openSettings}>操作键位不可用 · 打开设置修正</button>}
   {b.boss&&<div className="boss-bar"><div><BossIdentity b={b} art={art}/><small>{b.bossEnding>0?'脱身窗口 · '+Math.ceil(b.bossEnding)+' 秒':b.boss.type==='seal'?'敛息进度 · '+Math.floor(b.mechanism?.progress||0)+' / 42 秒':b.boss.type==='swarm'?'虫潮 · '+Math.ceil(b.boss.timer)+' 秒':b.boss.phaseShield>0?'护势 '+b.boss.phaseShield.toFixed(1)+' 秒 · 暂不可伤':'阶段 '+((b.boss.phase||0)+1)+' · 观察预警'}</small></div><div className="boss-track"><span style={{width:percent(b.boss.hp,b.boss.maxHp)+'%'}}/></div></div>}
   {b.midEncounter&&!b.midEncounter.done&&<div className="objective-note"><strong>{b.midEncounter.name}</strong><span>进入青色阵位 · {Math.floor(b.midEncounter.progress)} / 12 秒</span></div>}
   <div className="battle-side"><div className="starter-state" style={{color:PATHS[b.path].color}}><small>{PATHS[b.path].name}起手</small><strong>{starterStatus(b)}</strong></div>{(b.input.focus||b.objective?.kind==='defend'&&b.formation===2)&&<div className="focus-status">{b.touchLockId!=null?'触屏锁定 · '+(b.enemies.find(e=>e.id===b.touchLockId)?.name||'目标'):b.input.touchAim?'触屏定点集火 · 右上角或摇杆旁可解除':b.objective?.kind==='defend'&&b.formation===2?'护阵定向穿刺 · 切回分组并松开集火':directFocus(b)?b.objective?.kind==='defend'?'护阵单点集火 · 松开左键恢复剑式分配':'鼠标集火 · 新出击剑集中首目标':'鼠标指引 · 按当前剑式分配'}</div>}{cultivationStatus(b)&&<div className="cultivation-status">{cultivationStatus(b)}</div>}<CombatButton className="formation-label" onAction={()=>combatAction(()=>b.changeFormation())} title="点击切换剑式"><span>当前剑式</span><strong>{['分组追击','环绕护身','定向穿刺'][b.formation||0]}</strong><small>{keyLabel(keymap.formation)} 切换</small></CombatButton><small className="layout-label">{b.isExpedition?encounterLabel(b.encounter,b.chapter):layoutFor(b).name}</small>{b.isExpedition&&b.relics.filter(id=>CORES.some(c=>c.id===id)).map(id=><div className="active-combo" key={id}>{CORES.find(c=>c.id===id).name}</div>)}{b.combos.map(c=><div className="active-combo" key={c.name} title={comboDescription(c,b)}>{c.name}{c.effect==='swordPuppet'&&<small>{comboDescription(c,b)}</small>}</div>)}</div>
   {spaceLimited&&!landscapeDismissed&&<button className="small-window-advice" onClick={()=>setLandscapeDismissed(true)} title="战场空间不足，可放大窗口或横屏；点击关闭">小窗 · 放大/横屏 ×</button>}<CombatStatus b={b}/><footer ref={footerRef} className="battle-footer" onPointerDown={e=>e.stopPropagation()}><div className="progress-section"><CombatButton className="hud-summary-button" trigger="up" onAction={()=>{b.pause();clearAim();joy.current={x:0,y:0};heldKeysRef.current.clear();hudSummaryRef.current=true;setHudSummary(true);}}>战况 · {Math.min(72,b.level)}剑</CombatButton><CombatButton className="compact-formation-button" onAction={()=>combatAction(()=>b.changeFormation())} aria-label={'切换剑式，当前'+['分组追击','环绕护身','定向穿刺'][b.formation||0]}>剑式 ↻<span>{['分组','环绕','穿刺'][b.formation||0]}</span></CombatButton><div className="sword-counter"><CombatButton className="formation-toggle" onAction={()=>combatAction(()=>b.changeFormation())} title="点击切换剑式" aria-label={'切换剑式，当前'+['分组追击','环绕护身','定向穿刺'][b.formation||0]}>剑式 ↻</CombatButton><span className="formation-current">{['分组追击','环绕护身','定向穿刺'][b.formation||0]}</span><strong>{Math.min(72,b.level)}</strong><small>/ 72</small><b>进阶 {b.level}</b></div><div className="xp-track"><span style={{width:percent(b.xp,xpCostFor(b,b.level))+'%'}}/></div><div className="xp-label"><span>{b.level>=72?'御剑圆满 · 继续修持':'距下一把飞剑'}</span><span>{Math.floor(b.xp)} / {xpCostFor(b,b.level)}</span></div>{b.growth?.ledger&&!b.growth.ledger.settled&&<div className="growth-budget">{growthGuidance(b).text}<small>{growthGuidance(b).detail}</small></div>}<div className={"ally-counts "+(b.puppets.length||b.insects.length?"has-allies":"no-allies")}><span>傀儡 <b>{b.scene==='intro'?allyDeployment(b).puppets:b.puppets.length}</b></span><span className="gold-count">噬金虫 <b>{b.scene==='intro'?allyDeployment(b).insects:b.insects.length}</b></span>{b.scene==='intro'&&<small>入场后出战</small>}</div><div className="path-dots" title="以下数字为各方向已修持的不同战术种类"><small>修持种类</small>{PATHS.map((v,i)=><span style={{color:v.color}} key={v.id}>{v.icon} {b.pathCounts[i]}</span>)}</div></div>
    <div className="consumables">{[0,1].map(i=>{const state=b.itemReadiness(i);return <CombatButton key={i} onAction={()=>combatAction(()=>b.consume(i))} className={'consumable-slot '+(state.blocked?'resource-full':'')} title={state.label+' · '+(state.item?.desc||'空药囊')} disabled={!state.count}><kbd>{keyLabel(keymap['item'+(i+1)])}</kbd><span>{state.item?.name||'空药囊'}</span><small>× {state.count}{state.pendingBonus?' · 留有加赠药包':''}{state.summon?.label?' · '+state.summon.label:''}</small>{state.blocked&&<em>已满 · 保留</em>}</CombatButton>;})}</div>
    <div className="skill-controls"><CombatButton className={'dash-button '+(b.dashFeedback?.until>b.time?'dash-'+b.dashFeedback.kind:'')} onAction={()=>combatAction(()=>b.requestDash())} aria-disabled={p.dashCD>0} title={b.dashFeedback?.kind==='denied'&&b.dashFeedback.until>b.time?'闪避仍在冷却':p.dashCD>0?b.options.inputVersion===2?'冷却将尽时可提前120毫秒按下':'本局为即时输入，冷却结束后可闪避':'闪避已就绪'}><kbd>{keyLabel(keymap.dash)}</kbd><span>{b.dashFeedback?.until>b.time?b.dashFeedback.kind==='buffer'?'待闪避':b.dashFeedback.kind==='executed'?'已闪避':'冷却中':p.dashCD>0?p.dashCD.toFixed(1)+'s':'闪避'}</span>{b.rulesVersion>=2&&b.path===4&&<small className="sigil-ready">{b.sigilReadiness().label}</small>}</CombatButton><CombatButton className={'thunder-button '+(thunder.ready?'charged':p.reserve<thunder.cost?'reserve-empty':'')} onAction={()=>combatAction(()=>b.thunder())}><div className="charge-fill" style={{height:p.mana+'%'}}/><kbd>{keyLabel(keymap.thunder)}</kbd><strong>辟邪神雷</strong><small>{p.mana>=99.9&&p.reserve<thunder.cost?'灵力已满 · 雷源不足':thunder.label}</small></CombatButton><div className="reserve-label">{(b.puppets.length>0||b.insects.length>0)&&<span className="compact-allies">{b.puppets.length>0&&<>傀儡 {b.puppets.length} </>}{b.insects.length>0&&<>噬金虫 {b.insects.length}</>}</span>}<span>雷源 <b>{Math.floor(p.reserve)}</b> / {p.maxReserve}</span><small><span className="reserve-cost-number"> · 每次耗用 {thunder.cost} · </span><span className="reserve-uses">雷源可支撑 {Math.floor(p.reserve/thunder.cost)} 次</span></small><small className={b.isExpedition&&hasReserveRest(b)?'reserve-rest-hint':''}>{b.mode==='training'?'暂停可补满资源':b.isExpedition&&hasReserveRest(b)?'合格休整：基础'+reserveRestBase(b)+(b.stats.metaReserveRest?' + 修持'+b.stats.metaReserveRest:'')+'（上限内）':b.chapter===5&&b.mode!=='endless'?'终章雷源有限':'换章补满雷源'}</small></div></div>
   </footer>
   {b.practice&&<PracticePanel device={inputDevice} settings={save.settings} b={b} onExit={finishPractice} keymap={keymap} keyLabel={keyLabel}/>}
   {b.input.touchAim&&<CombatButton className="thumb-clear" onAction={releaseAim} aria-label="取消触屏瞄准" title="取消锁敌和定点瞄准">解除</CombatButton>}
   <div className="touch-joystick" onPointerDown={e=>{if(b.modeState!=='battle'||risk||help||joy.current.pointerId!==undefined||!capturePointer(e))return;joy.current={pointerId:e.pointerId,...joystickPoint(e)};}} onPointerMove={e=>{if(e.buttons&&joy.current.pointerId===e.pointerId)joy.current={pointerId:e.pointerId,...joystickPoint(e)};}} onPointerUp={e=>{if(joy.current.pointerId===e.pointerId)joy.current={x:0,y:0};}} onPointerCancel={e=>{if(joy.current.pointerId===e.pointerId)joy.current={x:0,y:0};}} onLostPointerCapture={e=>{if(joy.current.pointerId===e.pointerId)joy.current={x:0,y:0};}}><span/></div>
  </>}
  <Dialog open={!!scene&&isPlay&&!risk&&!help&&!runtimeFault&&!practiceOffer&&!resultRecords&&!hudSummary} onOpenChange={open=>{if(!open&&!riskRef.current&&!helpRef.current&&b?.modeState==='pause')b.resume();}}>
   <DialogContent initialFocus={scene==='cinematic'?cinematicFocusRef:['choice','pause'].includes(scene)?choiceFocusRef:undefined} className={'game-dialog scene-'+scene} showCloseButton={scene==='pause'}>
    <div className="dialog-heading" ref={choiceFocusRef} tabIndex={-1}><span className="eyebrow">{scene==='choice'?'进阶 '+b?.level+' · 飞剑 '+Math.min(72,b?.level||0)+' 把':scene==='result'?GAME_ARC+' · 历练':current.sub}</span><DialogTitle>{sceneTitles[scene]||'青竹剑阵'}</DialogTitle><DialogDescription>{scene==='choice'?'从可用战术中择一修持。每四级悟道一次，飞剑逐级自动增加。':scene==='intro'?(b?.mode==='training'?(b.options.guidedPractice?'按步骤练习移动、闪避、集火与神雷，使用正式起手数值；不结算正式节点，完成后返回出发配置。':'持续练习，不结算正式节点；暂停可补满资源。'):current.intro[0]):scene==='shop'?'从已携带的物资中调整配置，唯一古宝按剧情开放。':scene==='result'?'本次所得与保存状态见下方。':'灵息暂停，敌人不会继续行动。'}</DialogDescription></div>
    {scene==='intermission'&&b?.isExpedition&&<ExpeditionPanel b={b} save={save} art={art} onBuy={buyItem} onReplace={replaceItem} onSell={sellItem} onContinue={confirmRestDeparture} replace={replace} setReplace={setReplace}/>}
    {scene==='cinematic'&&b?.isExpedition&&<Cinematic b={b} art={art} gate={sceneInput.current} advanceRef={cinematicFocusRef}/>}
    {scene==='intro'&&<><PanelBody>{studyRun(b)&&<p className="training-guide">前两章对照体验 · 固定种子与空修持，不结算正式进度。暂停可填写笔记并导出观察包。</p>}<ChallengePanel b={b}/>{b.mode==='training'?<p className="training-guide">试剑台不完成节点、不领取历练奖励。暂停可补满资源，并切换 36／72 把飞剑。</p>:b.isExpedition&&<RouteStrip b={b}/>}<details className="run-cultivation"><summary>本局洞府修持 · {(b.options.metaRulesVersion??1)>=2?'仅启用'+PATHS[b.path].name+'分支':'旧局原配置'}</summary><CultivationSummary options={b.options} path={b.path}/></details><div className="chapter-intro"><span className="large-chapter">{current.tag}</span><div><p>{current.intro[1]}</p><p>{current.intro[2]}</p></div></div><div className="intro-loadout"><Chip color={PATHS[b.path].color}>{PATHS[b.path].name}起手</Chip><Chip>{b.difficulty.name}</Chip><Chip>{b.restored||b.resuming?'已恢复此局保存的出发配置':'七十二剑已炼成，逐步投入战斗'}</Chip></div><details className="run-guide" open={b.showGuide||b.rulesVersion<2} onToggle={e=>{b.showGuide=e.currentTarget.open;}}><summary>本局打法 · {b.rulesVersion<2?'旧局原规则':STARTERS[b.path].tag}</summary>{b.rulesVersion<2?<p>这份旧存档沿用改版前的起手配置，可继续本局。新的起手特点会在新历练中生效。</p>:<><p className="run-starting-stats">当前配置：{runConfiguration(b)}</p><p>基础起手与洞府：{starterDetails(b.path,b.options).initial}</p><p>{starterDetails(b.path,b.options).action}</p><p>入场协战：傀儡 {allyDeployment(b).puppets} 具 · 噬金虫 {allyDeployment(b).insects} 只。</p><small className="muted">当前配置已计入洞府、章节预置、悟道与携行；下列要点说明基础起手机制。</small><ol>{starterDetails(b.path,b.options).tips.map(t=><li key={t}>{t}</li>)}</ol></>}</details><StoryItemSummary b={b}/><RunStats b={b}/></PanelBody><div className="panel-action-dock">{!landscapeDismissed&&<button className="portrait-advice" onClick={()=>setLandscapeDismissed(true)}>横屏可看得更宽 · 点击关闭</button>}<Btn className="primary-start" onClick={()=>{b.start();canvasRef.current?.focus();}}>进入{current.name} <span>→</span></Btn><small className="muted">{inputDevice==='touch'? (touchSettings(save.settings).joystickSide==='right'?'右':'左')+'侧摇杆移动 · 点技能按钮 · 点战场集火，摇杆旁解除':'WASD 移动 · 自动御剑 · '+keyLabel(keymap.dash)+' 闪避 · '+keyLabel(keymap.thunder)+' 神雷'}</small><Btn variant="ghost" onClick={home}>返回山门</Btn></div></>}
    {scene==='choice'&&<><PanelBody><section className="choice-chain"><strong>待悟道 {choiceChain(b).remaining} 次（含本次）</strong><p>上次选择：{choiceChain(b).last}</p>{choiceChain(b).gain&&<p>当前配置变化：{choiceChain(b).gain}（加成层，不含条件触发）</p>}<details><summary>本路联动还差多少种</summary>{choiceChain(b).links.map(text=><p key={text}>{text}</p>)}</details><small>已生成候选随保存恢复；上次选择只解释本次所得，不再发奖。</small></section><p className="muted choice-note">{revisedGrowth(b)?'按当前配置筛选；首次有本路可用项时保底一张。当前可选 '+b.choices.length+' 项，数值强化最多重复修持3次；独立效果只学1次，不代表品质。':'旧局沿用原候选池。数值强化最多重复修持3次；独立效果只学1次，不代表品质。跨路倍率需相应单位。'}</p><div className="choice-grid">{b.choices.map(t=><article key={t.id} className="choice-card" style={{'--path-color':PATHS[t.path].color}}><div className="choice-top"><span>{PATHS[t.path].name}</span><small>{t.max===1?'独立效果':'可叠加强化'}</small></div><div className="choice-sigil">{PATHS[t.path].icon}</div><h3>{t.name}</h3><p>{traitDescription(t,b)}</p><small className="trait-values">{traitTierName(t)}{traitValueLine(t,b)?' · '+traitValueLine(t,b):''}</small>{traitComboBenefit(t,b)&&<p className="trait-condition">{traitComboBenefit(t,b)}</p>}{revisedGrowth(b)&&traitReadiness(t,b).reason&&<small className="trait-condition">{traitReadiness(t,b).reason}</small>}<footer><span>{t.max===1?'仅可修持一次':'本次为第 '+((b.traits[t.id]||0)+1)+' / '+t.max+' 次'}</span><SceneAction gate={sceneInput.current} onAction={()=>b.chooseTrait(t.id)} aria-label={'选择 '+t.name+'（卡片任意位置均可点）'}>选择 →</SceneAction></footer></article>)}</div></PanelBody><div className="dialog-actions panel-action-dock"><span className="muted">两个方向各修持三种，可形成流派联动。</span><SceneAction gate={sceneInput.current} onAction={()=>b.reroll()} disabled={b.rerolls<=0}>重选 · 剩余 {b.rerolls}</SceneAction></div></>}
    {scene==='event'&&<><p className="event-description">{EVENTS[b.eventIndex].desc}</p><div className="event-choices">{EVENTS[b.eventIndex].choices.map(c=><button key={c.effect} onClick={()=>b.chooseEvent(c.effect)}><div><strong>{c.name}</strong><small>{c.desc}</small></div><span>→</span></button>)}</div><small className="muted">战术遭遇，不改变原著关键事件。</small></>}
    {scene==='shop'&&<><div className="resource-line"><span>灵石 <b>{b.gold}</b></span><Btn variant="outline" onClick={()=>b.refreshShop()} disabled={b.gold<10+b.shopRolls*8}>重整 · {10+b.shopRolls*8} 灵石</Btn></div><div className="shop-grid">{b.shop.map((r,i)=><article className={'shop-card '+(b.purchased.includes(r.id)?'purchased':'')} key={r.id}><Chip>{r.kind==='consumable'?'行囊物资':r.story?'原著器物':'携行配置'}</Chip><h3>{r.name}</h3><p>{r.mods?modText(r.mods):r.desc}</p><div><Btn variant="outline" disabled={b.purchased.includes(r.id)||b.gold<r.price} onClick={()=>buyItem(i)}>{b.purchased.includes(r.id)?'已取用':r.price+' 灵石'}</Btn>{r.kind==='relic'&&<button className="lock-button" title="保留到下次整备" onClick={()=>{b.toggleLock(i);redraw(v=>v+1);}}>{b.locked.some(x=>x.id===r.id)?'◆':'◇'}</button>}</div></article>)}</div>
     <div className="equipped"><span>{replace!==null?(b.shop[replace]?.kind==='consumable'?'选择要替换的药囊':'选择要替换的配置'):'已装备 '+b.relics.length+' / 6 · 点击回收得 25 灵石'}</span><div>{replace!==null&&b.shop[replace]?.kind==='consumable'?b.consumables.map((slot,i)=><button key={i} onClick={()=>{b.buy(replace,i);setReplace(null);redraw(v=>v+1);}}>{CONSUMABLES.find(c=>c.id===slot.id)?.name} ×{slot.count} ↔</button>):b.relics.map((id,i)=><button key={id} onClick={()=>{if(replace!==null){b.buy(replace,i);setReplace(null);}else b.sell(i);redraw(v=>v+1);}}>{RELICS.find(r=>r.id===id)?.name} {replace!==null?'↔':'×'}</button>)}{replace!==null&&<button onClick={()=>setReplace(null)}>取消替换</button>}</div></div><Btn className="primary-start" onClick={()=>b.continueRest()}>整装继续 <span>→</span></Btn></>}
    {scene==='pause'&&<>{(studyRun(b)||[1,2].includes(b.options.challengeVersion))&&<ObservationPanel b={b} onExport={exportObservation} onNotes={notes=>{b.observationNotes=notes;}}/>}<div className="pause-stats"><span>御剑 <b>{Math.min(72,b.level)}</b></span><span>斩敌 <b>{b.kills}</b></span><span>雷源 <b>{Math.floor(p.reserve)}</b></span></div><p className="muted">{b.mode==='training'?'持续训练，不结算节点；资源可在下方补满':current.objective}。{b.combos.length?'已成联动：'+b.combos.map(c=>c.name).join('、'):'每四级选择一次战术强化。'}</p>{b.mode==='training'&&<div className="mode-row">{b.options.metaRulesVersion>=2&&<Btn variant="outline" onClick={()=>{b.level=b.level===72?36:72;b.swords=[];b.syncSwords();b.recalc();redraw(v=>v+1);}}>{b.level===72?'切换 36 剑试招':'切换 72 剑试招'}</Btn>}<Btn variant="outline" onClick={()=>{b.player.hp=b.player.maxHp;b.player.mana=100;b.player.reserve=b.player.maxReserve;redraw(v=>v+1);}}>补满试剑资源</Btn><Btn variant="outline" onClick={()=>{b.queuedChoices++;b.openChoices();}}>研习一项战术</Btn></div>}<section className="checkpoint-status"><strong>{studyRun(b)?'观察未写入正式进度 · 请导出观察包保存':b.mode==='training'?'试剑台不写入正式进度':saveStatus==='saved'?'最近保存成功':'保存状态：'+(saveStatus==='conflict'?'另一窗口有新记录':'需处理或等待')}</strong>{b.mode!=='training'&&!studyRun(b)&&<p>{describeSave(save)} · {save.checkpoint?'此后未保存战斗约 '+Math.max(0,Math.floor(b.time-save.checkpoint.time))+' 秒':'本局暂无续玩快照'}</p>}</section>{invalidBindings(keymap).length>0&&<p className="key-warning">有不可用或重复键位，请在设置中重新绑定；旧键位未自动改写。</p>}<Btn className="primary-start" onClick={()=>b.resume()}>继续历练</Btn><Btn variant="outline" onClick={openSettings}>音画与操控设置</Btn><Btn variant="outline" onClick={()=>openHelp('guide')}>游玩说明</Btn><Btn variant="outline" onClick={home}>返回山门 · 最近节点续玩</Btn><ChapterReview b={b} save={save}/><RunStats b={b}/>{b.growth?.ledger&&<p className="growth-explanation">节点基础已拾取 {Number(b.growth.ledger.baseCollected.toFixed(1))}；表现经验 +{Number(b.growth.ledger.bonusCollected.toFixed(1))}（上限 {b.node.xp*.25}）。基础不足在通关时补足，表现奖励不抵扣保底。</p>}<RecentHits b={b}/></>}
    {scene==='chapterEnd'&&<><div className="chapter-intro"><span className="large-chapter">{current.tag}</span><div><p>{current.outro}</p><p className="muted">灵石已结算，继续前行时恢复部分生命并完成关间准备。</p></div></div><div className="pause-stats"><span>御剑 <b>{Math.min(72,b.level)}</b></span><span>斩敌 <b>{b.kills}</b></span><span>历时 <b>{clock(elapsedBattle(b)??b.time)}</b></span></div><Btn className="primary-start" onClick={()=>b.nextChapter()}>{b.chapter===5&&b.mode!=='endless'?'收拢所得 · 结算':'继续前往 '+CHAPTERS[(b.chapter+1)%6].name} <span>→</span></Btn></>}
    {scene==='result'&&<><div className="result-hero"><SpriteView art={art} height={95}/><p>{b.won?'寻得机缘，亦知进退。此行所得，皆是日后修行的根基。':(b.failureReason?b.failureReason+'。':'')+'留得修行心得，来日再探此境。'}</p></div><div className="result-stats">{[['斩敌',b.kills],['御剑',Math.min(72,b.level)],['神雷',b.thunders],[b.summary().recordDetails?'净战斗时间':'旧局历时',b.summary().recordDetails?formatRecordTime(b.summary().recordDetails.battleMs):clock(b.time)],[studyRun(b)?'观察不结算':'心得','+'+b.summary().insight]].map(([k,v])=><div key={k}><small>{k}</small><strong>{v}</strong></div>)}</div><>{b.won&&b.isExpedition&&<p className="ending-count-note">玄骨因圣火反噬而亡，不计入普通斩敌；终局节点与历练完成照常结算。</p>}<StoryItemSummary b={b}/></>{(studyRun(b)||[1,2].includes(b.options.challengeVersion))&&<ObservationPanel b={b} onExport={exportObservation} onNotes={notes=>{b.observationNotes=notes;}}/>}<ResultRecord b={b} save={save} onRetry={retryPendingResult} onExport={exportPendingResult} onOpen={()=>setResultRecords(true)}/>{b.isExpedition&&!studyRun(b)&&<p className="muted">完成 {b.receipts.length} / 22 节点 · 药园研究 +{b.research} 点（正式主篇／定种结算）</p>}{!b.won&&<section className="defeat-advice"><h3>下次可以尝试</h3>{defeatAdvice(b).map(text=><p key={text}>{text}</p>)}</section>}<RecentHits b={b}/><DamageReport b={b}/><SigilReport b={b}/><div className="dialog-actions"><Btn variant="outline" onClick={home}>回到洞府</Btn><Btn className="primary-start" onClick={()=>studyRun(b)?start(studyOptions(b.path)):start()}>{studyRun(b)?'再做本路观察 →':'再历此境 →'}</Btn></div></>}
   </DialogContent>
  </Dialog>
  <Dialog open={hudSummary&&!risk} onOpenChange={value=>{hudSummaryRef.current=value;setHudSummary(value);}}><DialogContent className="game-dialog hud-summary-dialog"><DialogTitle>当前战况</DialogTitle><DialogDescription>战斗已暂停。关闭摘要后，由你继续战斗。</DialogDescription><PanelBody>{b&&<><p>灵石 {b.gold} · 斩敌 {b.kills} · 净战斗 {clock(elapsedBattle(b)??b.time)}</p><p>{starterStatus(b)}{cultivationStatus(b)&&<> · {cultivationStatus(b)}</>}</p><p>飞剑 {Math.min(72,b.level)} / 72 · 进阶 {b.level} · 经验 {Math.floor(b.xp)} / {xpCostFor(b,b.level)}</p><p>傀儡 {b.puppets.length} 具 · 噬金虫 {b.insects.length} 只</p><p>灵力 {Math.floor(b.player.mana)} / 100 · 雷源 {Math.floor(b.player.reserve)} / {b.player.maxReserve} · 每次神雷耗用 {thunder.cost} 雷源</p>{b.growth?.ledger&&<p>{growthGuidance(b).text}。{growthGuidance(b).detail}</p>}<RunStats b={b}/></>}</PanelBody><div className="panel-action-dock"><Btn onClick={()=>{hudSummaryRef.current=false;setHudSummary(false);}}>关闭摘要 · 保持暂停</Btn></div></DialogContent></Dialog>
  <Dialog open={resultRecords&&!risk} onOpenChange={setResultRecords}><DialogContent className="game-dialog result-records-dialog"><DialogTitle>个人最佳与最近尝试</DialogTitle><DialogDescription>本设备记录 · 关闭后返回本次结算</DialogDescription><PanelBody><RecordsPanel save={save}/></PanelBody><Btn variant="outline" onClick={()=>setResultRecords(false)}>返回本次结算</Btn></DialogContent></Dialog>
  <Dialog open={!!practiceOffer&&!risk} onOpenChange={open=>{if(!open)setPracticeOffer(null);}}><DialogContent className="game-dialog practice-offer"><DialogTitle>先练习走位与御剑？</DialogTitle><DialogDescription>约一分钟的分步操作练习，不消耗物资，不结算奖励。也可以直接出发。</DialogDescription><div className="dialog-actions"><Btn variant="outline" onClick={()=>{const chosen=practiceOffer;setPracticeOffer(null);practiceAcknowledged.current=true;start({...chosen,skipPractice:true});}}>直接出发</Btn><Btn onClick={()=>{const chosen=practiceOffer;practiceReturn.current=chosen;setPracticeOffer(null);start({...chosen,mode:'training',guidedPractice:true,skipPractice:true});}}>练习后出发</Btn></div></DialogContent></Dialog>
  <Dialog open={!!help&&!risk} onOpenChange={open=>{if(!open)closeHelp();}}><DialogContent className="game-dialog help-dialog"><DialogTitle>{help==='license'?'开源许可与源码':help==='changes'?'更新日志':'游玩说明'}</DialogTitle><DialogDescription>青竹剑阵 · {GAME_VERSION} · 阅读期间战斗暂停</DialogDescription><HelpReader key={help||'guide'} kind={help||'guide'} open={!!help}/><Btn variant="outline" onClick={closeHelp}>关闭说明</Btn></DialogContent></Dialog>
  <AlertDialog open={!!risk} onOpenChange={open=>{if(!open)cancelRisk();}}><AlertDialogContent className="game-dialog risk-dialog" initialFocus={cancelRiskRef}><span className="eyebrow">{risk?.kind==='equipment'?'携行变更确认':'存档保护'}</span><AlertDialogTitle>{risk?.title}</AlertDialogTitle><AlertDialogDescription>{risk?.description}</AlertDialogDescription><p className="risk-detail">{risk?.detail}</p>{risk?.comparison&&<SaveComparison {...risk.comparison}/>}<small>{risk?.footnote||(risk?.kind==='equipment'?'确认前不改变携行或灵石；确认后保留变更前的存档备份。':'备份包含最近可恢复节点与已结算记录，当前波次未保存进度可能回退。')}</small><div className="risk-actions"><Btn variant="outline" onClick={cancelRisk} ref={cancelRiskRef}>取消 · 保留当前状态</Btn><Btn variant="outline" onClick={risk?.onExport||(risk?.recovery?exportRecovery:exportSave)}>{risk?.exportLabel||(risk?.recovery?'导出原文':'导出备份')}</Btn>{risk?.recovery&&<Btn onClick={()=>{cancelRisk();openSettings();}}>查看恢复方案</Btn>}{risk?.run&&<Btn className="risk-confirm" onClick={confirmRisk} disabled={!!risk.replaced}>{risk.confirm}</Btn>}</div></AlertDialogContent></AlertDialog>
  {runtimeFault&&!risk&&<section className="runtime-recovery"><h2>本局已暂停保护</h2><p>最近的保存记录未被覆盖。导出后可载入最近节点；如果仍有异常，请导出后刷新页面。</p><div className="mode-row"><Btn variant="outline" onClick={exportSave}>导出备份</Btn><Btn disabled={!save.checkpoint} onClick={recoverRuntime}>恢复最近节点</Btn><Btn variant="outline" onClick={home}>返回山门</Btn></div></section>}
  {toast&&<output className="game-toast" title={toast}>{toast}</output>}
 </main>;
}
